-- phpMyAdmin SQL Dump
-- version 5.1.0
-- https://www.phpmyadmin.net/
--
-- Máy chủ: 127.0.0.1
-- Thời gian đã tạo: Th6 20, 2021 lúc 12:50 AM
-- Phiên bản máy phục vụ: 10.4.19-MariaDB
-- Phiên bản PHP: 8.0.6

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Cơ sở dữ liệu: `book`
--

-- --------------------------------------------------------

--
-- Cấu trúc bảng cho bảng `book`
--

CREATE TABLE `book` (
  `id` int(11) NOT NULL,
  `name` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `slug` varchar(550) COLLATE utf8_unicode_ci DEFAULT NULL,
  `img` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `type` tinyint(1) NOT NULL,
  `class` int(2) NOT NULL,
  `author` varchar(100) COLLATE utf8_unicode_ci NOT NULL,
  `publishing` varchar(100) COLLATE utf8_unicode_ci NOT NULL,
  `year` varchar(4) COLLATE utf8_unicode_ci NOT NULL,
  `description` longtext COLLATE utf8_unicode_ci DEFAULT NULL,
  `link` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `part` tinyint(1) DEFAULT NULL,
  `idcate` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Đang đổ dữ liệu cho bảng `book`
--

INSERT INTO `book` (`id`, `name`, `slug`, `img`, `type`, `class`, `author`, `publishing`, `year`, `description`, `link`, `part`, `idcate`) VALUES
(1, 'Smart Time Special Edition Grade 12 - Student\'s book', 'smart-time-special-edition-grade-12---student\'s-book-1', 'ST12-WB_GB.png', 1, 12, 'Virginia Evans - Jenny Dooley', 'Hợp tác xuất bản cùng Express Publishing', '2020', 'Cuốn Smart time Special Edition Grade 12 Student\'s Book là cuốn sách dành cho học sinh lớp 12. Cấu trúc của cuốn sách như sau:<br>\r\n- Phần Mở đầu (Stater) <br>\r\n- 9 đơn vị bài học (unit) được thiết kế dựa vào chủ đề (theme-based): Living together; Survival; Work; Entertainment; Can you Help; Don’t be Afraid; Health & Food; Amazing Journay; Getting Connected. <br>\r\nMỗi đơn vị bài học gồm 6-7 bài học (lesson) (tổng số khoảng 54-63 bài học) và một bài kiểm tra sự tiến bộ của học sinh, phần Progress check (Kiểm tra tiến bộ) gồm các mục Đọc (Reading) kèm theo băng Video, Tiếng Anh hàng ngày (Everyday English), Nghe (Listening), Từ vựng (Vocabulary), Ngữ pháp (Grammar), và Viết (Writing) và Mục Các năng lực (Competences) để học sinh tự đánh giá khả năng của mình trong 4 kĩ năng nghe, nói, đọc và viết. Mỗi đơn vị bài học được tổ chức xung quanh 10 nội dung: Từ vựng (Vocabulary), Ngữ pháp (Grammar), Đọc (Reading), Nghe (Listening), Phát âm (Pronunciation), Nói/chức năng và kĩ năng trình bày (Speaking/Functions & Presentation Skills), Viết (Writing), Văn hoá (Culture, and CLIL). Tất cả các đơn vị bài học và các bài đều đi theo cấu trúc cơ bản giống nhau. <br>\r\n- Cuối 9 đơn vị bài học là mục Kĩ năng trình bày (Presentation Skills) (gồm 5 mục nhỏ) trình bày và hướng dẫn học sinh cách trình bày bằng khẩu ngữ; Thực hành thi (Exam Practice) (gồm 5 bài thi) gồm đọc (reading), nói (speaking), nghe (listening), viết (writing); học để học (learning to learn) cung cấp một số kĩ năng học, đọc, trả lời câu hỏi; Tham khảo ngữ pháp (Grammar reference) cung cấp lí thuyết và thực hành làm các bài tập cho từng đơn vị bài học, Danh mục từ vựng (Word list), và phần Hướng dẫn tiếng Anh-Anh và tiếng Anh-Mĩ (British and American Guide)', '', NULL, 3),
(2, 'Smart Time Special Edition Grade 11 - Student\'s book', 'smart-time-special-edition-grade-11---student\'s-book-2', 'ST11-WB_GB.png', 1, 11, 'Virginia Evans - Jenny Dooley', 'Hợp tác xuất bản cùng Express Publishing', '2018', 'Cuốn Smart time Special Edition Grade 11 Student\'s Book là cuốn sách dành cho học sinh lớp 11. Cấu trúc của cuốn sách như sau: <br>\r\n- Phần Mở đầu (Stater) <br>\r\n- 9 đơn vị bài học (unit) được thiết kế dựa vào chủ đề (theme-based): Just the job; Nature’s fury; Reflections; Law & Order; High Tech; Healthy Mind & H. Body; Global Issues; Creative Minds; Teen Spotlight <br>\r\nMỗi đơn vị bài học gồm 6-7 bài học (lesson) (tổng số khoảng 54-63 bài học) và một bài kiểm tra sự tiến bộ của học sinh, phần Progress check (Kiểm tra tiến bộ) gồm các mục Đọc (Reading) kèm theo băng Video, Tiếng Anh hàng ngày (Everyday English), Nghe (Listening), Từ vựng (Vocabulary), Ngữ pháp (Grammar), và Viết (Writing) và Mục Các năng lực (Competences) để học sinh tự đánh giá khả năng của mình trong 4 kĩ năng nghe, nói, đọc và viết. Mỗi đơn vị bài học được tổ chức xung quanh 10 nội dung: Từ vựng (Vocabulary), Ngữ pháp (Grammar), Đọc (Reading), Nghe (Listening), Phát âm (Pronunciation), Nói/chức năng và kĩ năng trình bày (Speaking/Functions & Presentation Skills), Viết (Writing), Văn hoá (Culture, and CLIL). Tất cả các đơn vị bài học và các bài đều đi theo cấu trúc cơ bản giống nhau. <br>\r\n- Cuối 9 đơn vị bài học là mục Kĩ năng trình bày (Presentation Skills) (gồm 5 mục nhỏ) trình bày và hướng dẫn học sinh cách trình bày bằng khẩu ngữ; Thực hành thi (Exam Practice) (gồm 5 bài thi) gồm đọc (reading), nói (speaking), nghe (listening), viết (writing); học để học (learning to learn) cung cấp một số kĩ năng học, đọc, trả lời câu hỏi; Tham khảo ngữ pháp (Grammar reference) cung cấp lí thuyết và thực hành làm các bài tập cho từng đơn vị bài học, Danh mục từ vựng (Word list), và phần Hướng dẫn tiếng Anh-Anh và tiếng Anh-Mĩ (British and American Guide)', '', NULL, 3),
(3, 'Smart Time Special Edition Grade 10 - Student\'s book', 'smart-time-special-edition-grade-10---student\'s-book-3', 'ST-gr10-VIET-Ss-cover-1.png', 1, 10, 'Virginia Evans - Jenny Dooley', 'Hợp tác xuất bản cùng Express Publishing', '2018', 'Cuốn sách SMART - GRADE 10 là cuốn sách mở đầu cho học sinh học tiếng Anh ở cấp THPT. <br>\r\nCuốn Smart time Special Edition Grade 10 Student\'s Book là cuốn sách dành cho học sinh lớp 10. Cấu trúc của cuốn sách như sau:\r\n-Phần Mở đầu (Stater) <br>\r\n- 9 đơn vị bài học (unit) được thiết kế dựa vào chủ đề (theme-based): Just the job; Nature’s fury; Reflections; Law & Order; High Tech; Healthy Mind & H. Body; Global Issues; Creative Minds; Teen Spotlight <br>\r\nMỗi đơn vị bài học gồm 6-7 bài học (lesson) (tổng số khoảng 54-63 bài học) và một bài kiểm tra sự tiến bộ của học sinh, phần Progress check (Kiểm tra tiến bộ) gồm các mục Đọc (Reading) kèm theo băng Video, Tiếng Anh hàng ngày (Everyday English), Nghe (Listening), Từ vựng (Vocabulary), Ngữ pháp (Grammar), và Viết (Writing) và Mục Các năng lực (Competences) để học sinh tự đánh giá khả năng của mình trong 4 kĩ năng nghe, nói, đọc và viết. Mỗi đơn vị bài học được tổ chức xung quanh 10 nội dung: Từ vựng (Vocabulary), Ngữ pháp (Grammar), Đọc (Reading), Nghe (Listening), Phát âm (Pronunciation), Nói/chức năng và kĩ năng trình bày (Speaking/Functions & Presentation Skills), Viết (Writing), Văn hoá (Culture, and CLIL). Tất cả các đơn vị bài học và các bài đều đi theo cấu trúc cơ bản giống nhau.<br>\r\n- Cuối 9 đơn vị bài học là mục Kĩ năng trình bày (Presentation Skills) (gồm 5 mục nhỏ) trình bày và hướng dẫn học sinh cách trình bày bằng khẩu ngữ; Thực hành thi (Exam Practice) (gồm 5 bài thi) gồm đọc (reading), nói (speaking), nghe (listening), viết (writing); học để học (learning to learn) cung cấp một số kĩ năng học, đọc, trả lời câu hỏi; Tham khảo ngữ pháp (Grammar reference) cung cấp lí thuyết và thực hành làm các bài tập cho từng đơn vị bài học, Danh mục từ vựng (Word list), và phần Hướng dẫn tiếng Anh-Anh và tiếng Anh-Mĩ (British and American Guide).', '', NULL, 3),
(4, 'Spark Special Edition Grade 9 - Student\'s Book', 'spark-special-edition-grade-9---student\'s-book-4', 'SPgr9VSs_cover-1.png', 1, 9, 'Virginia Evans - Jenny Dooley', 'Hợp tác xuất bản cùng Express Publishing', '2018', 'Cuốn sách SPARK - GRADE 9 được biên soạn dành cho các em học sinh học tiếng Anh ở lớp 9. <br>\r\nCấu trúc và nội dung cuốn sách như sau: Bao gồm các phần: <br>\r\n-  Phần Khởi động (Starter) <br>\r\n-  8 mô đun (module) được thiết kế dựa vào chủ đề (theme-based) bao gồm:<br> Celebrations; Strange but true; All things high tech; Survival; Art; Helping Hands; Challenges; Life & Living<br>\r\nMỗi mô đun/chủ đề gồm 8 nội dung dưới đây:<br>\r\n1. Từ vựng (Vocabulary) với một vài hoạt động làm quen với chủ đề của môđun<br>\r\n2. Đọc (Reading) với các hoạt động đa dạng<br>\r\n3. Ngữ pháp (Grammar) với các hoạt động đa dạng,<br>\r\n4. Các kĩ năng (Skills) bao gồm Đọc (Reading), Nghe (Listening), Nói (Speaking), Viết (Writing) với các hoạt động đa dạng<br>\r\n5. Tiếng Anh hằng ngày (Everyday English)<br>\r\n6. Giao văn hoá (Across Culture)<br>\r\n7. Viết (Writing)<br>\r\n8. Thời gian vui chơi (Fun Time).\r\nSau 8 mô đun là:<br>\r\n- 8 Language Reviews<br>\r\n- 8 Self-Checks<br>\r\n- ASEAN CULTURES giới thiệu về các nước ASEAN<br>\r\nCuốn sách SPARK - GRADE 9 chắc chắn sẽ là cẩm nang hữu ích và là người bạn đồng hành cùng các em học sinh trong quá trình chinh phục môn tiếng Anh.', '', NULL, 3),
(5, 'Spark Special Edition Grade 8 - Student\'s Book', 'spark-special-edition-grade-8---student\'s-book-5', 'SparkG8vtm_Ss_cover-1.png', 1, 8, 'Virginia Evans - Jenny Dooley', 'Hợp tác xuất bản cùng Express Publishing', '2018', 'Cuốn sách SPARK - GRADE 8 được biên soạn dành cho các em học sinh học tiếng Anh ở lớp 8.<br>\r\nCấu trúc và nội dung cuốn sách như sau: Bao gồm các phần:<br>\r\n-  Phần Khởi động (Starter)<br>\r\n-  8 mô đun (module) được thiết kế dựa vào chủ đề (theme-based) bao gồm: Lifestyle; Believe it or not; Experiences; Safe and sound; Our blue planet; Technology & Communication; Entertainment; Places & Life Styles<br>\r\nMỗi mô đun/chủ đề gồm 8 nội dung dưới đây:<br>\r\n1. Từ vựng (Vocabulary) với một vài hoạt động làm quen với chủ đề của môđun<br>\r\n2. Đọc (Reading) với các hoạt động đa dạng<br>\r\n3. Ngữ pháp (Grammar) với các hoạt động đa dạng,<br>\r\n4. Các kĩ năng (Skills) bao gồm Đọc (Reading), Nghe (Listening), Nói (Speaking), Viết (Writing) với các hoạt động đa dạng<br>\r\n5. Tiếng Anh hằng ngày (Everyday English)<br>\r\n6. Giao văn hoá (Across Culture)<br>\r\n7. Viết (Writing)<br>\r\n8. Thời gian vui chơi (Fun Time).<br>\r\nSau 8 mô đun là:<br>\r\n- 8 Language Reviews<br>\r\n- 8 Self-Checks<br>\r\n- ASEAN CULTURES giới thiệu về các nước ASEAN<br>\r\nCuốn sách SPARK - GRADE 8 chắc chắn sẽ là cẩm nang hữu ích và là người bạn đồng hành cùng các em học sinh trong quá trình chinh phục môn tiếng Anh.', '', NULL, 3),
(6, 'Spark Special Edition Grade 7 - Student\'s Book', 'spark-special-edition-grade-7---student\'s-book-6', 'Spark-gr7-VIET-Ss_cover-1.png', 1, 7, 'Virginia Evans - Jenny Dooley', 'Hợp tác xuất bản cùng Express Publishing', '2018', 'Cấu trúc và nội dung cuốn sách như sau: Bao gồm các phần: <br>\r\n-  Phần Khởi động (Starter)<br>\r\n-  8 mô đun (module) được thiết kế dựa vào chủ đề (theme-based) bao gồm: Back to school; Cool Stuff; Homes; Families; Great animals; Weather & Clothes; Food; Master of Art<br>\r\nMỗi mô đun/chủ đề gồm 8 nội dung dưới đây:<br>\r\n1. Từ vựng (Vocabulary) với một vài hoạt động làm quen với chủ đề của môđun<br>\r\n2. Đọc (Reading) với các hoạt động đa dạng<br>\r\n3. Ngữ pháp (Grammar) với các hoạt động đa dạng,<br>\r\n4. Các kĩ năng (Skills) bao gồm Đọc (Reading), Nghe (Listening), Nói (Speaking), Viết (Writing) với các hoạt động đa dạng<br>\r\n5. Tiếng Anh hằng ngày (Everyday English)<br>\r\n6. Giao văn hoá (Across Culture)<br>\r\n7. Viết (Writing)<br>\r\n8. Thời gian vui chơi (Fun Time).<br>\r\nSau 8 mô đun là:<br>\r\n- 8 Language Reviews<br>\r\n- 8 Self-Checks<br>\r\n- ASEAN CULTURES giới thiệu về các nước ASEAN<br>\r\nCuốn sách SPARK - GRADE 7 chắc chắn sẽ là cẩm nang hữu ích và là người bạn đồng hành cùng các em học sinh trong quá trình chinh phục môn tiếng Anh.', '', NULL, 3),
(7, 'Spark Special Edition Grade 6 - Student\'s Book', 'spark-special-edition-grade-6---student\'s-book-7', 'SparkG6_Ss_cover-1.png', 1, 6, 'Virginia Evans - Jenny Dooley', 'Hợp tác xuất bản cùng Express Publishing', '2018', 'Cuốn sách SPARK - GRADE 6 là cuốn sách mở đầu cho học sinh học tiếng Anh ở cấp THCS.<br>\r\nCấu trúc và nội dung cuốn sách như sau: Bao gồm các phần:<br>\r\n-  Phần Khởi động (Starter)<br>\r\n-  8 mô đun (module) được thiết kế dựa vào chủ đề (theme-based) bao gồm: Back to school; Cool Stuff; Homes; Families; Great animals; Weather & Clothes; Food; Master of Art<br>\r\nMỗi mô đun/chủ đề gồm 8 nội dung dưới đây:<br>\r\n1. Từ vựng (Vocabulary) với một vài hoạt động làm quen với chủ đề của môđun<br>\r\n2. Đọc (Reading) với các hoạt động đa dạng<br>\r\n3. Ngữ pháp (Grammar) với các hoạt động đa dạng,<br>\r\n4. Các kĩ năng (Skills) bao gồm Đọc (Reading), Nghe (Listening), Nói (Speaking), Viết (Writing) với các hoạt động đa dạng<br>\r\n5. Tiếng Anh hằng ngày (Everyday English)<br>\r\n6. Giao văn hoá (Across Culture)<br>\r\n7. Viết (Writing)<br>\r\n8. Thời gian vui chơi (Fun Time).<br>\r\nSau 8 mô đun là:<br>\r\n- 8 Language Reviews<br>\r\n- 8 Self-Checks<br>\r\n- ASEAN CULTURES giới thiệu về các nước ASEAN<br>\r\nCuốn sách SPARK - GRADE 6 chắc chắn sẽ là cẩm nang hữu ích và là người bạn đồng hành cùng các em học sinh trong quá trình chinh phục môn tiếng Anh.', '', NULL, 3),
(8, 'Smiles Special Edition Grade 5 - Activity Book', 'smiles-special-edition-grade-5---activity-book-8', 'S5-AB.png', 1, 5, 'Virginia Evans - Jenny Dooley', 'Hợp tác xuất bản cùng Express Publishing', '2018', 'Smiles Special Edition Grade 5 - Activity Book là sách bổ trợ cho cuốn sách học sinh, được thiết kế với 6 mô đun tương ứng với 6 mô đun trong Sách học sinh, chứa đựng các họat động giao tiếp đa dạng để phát triển 4 kĩ năng nghe, nói, đọc, viết và rèn luyện ngữ pháp và từ vựng.<br>\r\nMỗi mô đun trong sách bài tập gồm các dạng bài:<br>\r\n-  Lesson 1 & 2: tập trung luyện tập kĩ năng đọc-viết<br>\r\n-  Lesson 3 & 4 : luyện kĩ năng đọc chuyện<br>\r\n-  Lesson 5, 6, 7: luyện tập ngữ pháp và từ vựng<br>\r\n-  Lesson 8: luyện kĩ năng nghe<br>\r\nKết thúc mỗi mô đun là phần check point.<br>\r\nCuối mỗi cuốn Sách bài tập - Activity book là nội dung Welcome to Asian Countries và Story cutouts và một số các nội dung khác liên quan đến các nội dung văn hoá của thế giới và của nước nói tiếng Anh.', '', NULL, 3),
(9, 'Smiles Special Edition Grade 5 - Student\'s book', 'smiles-special-edition-grade-5---student\'s-book-9', 'S5-PB.png', 1, 5, 'Virginia Evans - Jenny Dooley', 'Hợp tác xuất bản cùng Express Publishing', '2018', 'Cấu trúc của Smiles Special Edition Grade 5 - Student\'s book bao gồm phần Khởi động (Let’s Start) và 6 mô đun (module) được thiết kế dựa vào chủ đề (theme-based) như: Water Sports, Funny clothes, A great zoo, Sorry Miss, A funny day, Special Days.\r\nMỗi mô đun/chủ đề tập trung vào các nội dung ngôn ngữ: từ vựng, cấu trúc câu, ngữ âm và phần mở rộng Project. Sau mỗi module gồm hai phần: Smiles Magazine và Time for CLIL (Content Language Integrated Learning).<br>\r\nSau 6 mô đun là các nội dung giới thiệu về văn hoá, xã hội của các nước trên thế giới và châu Á hay một số nội dung khác trong từng textbook cụ thể.<br>\r\nSmiles Special Edition Grade 5 - Activity Book là sách bổ trợ cho cuốn sách học sinh, được thiết kế với 6 mô đun tương ứng với 6 mô đun trong Sách học sinh, chứa đựng các họat động giao tiếp đa dạng để phát triển 4 kĩ năng nghe, nói, đọc, viết và rèn luyện ngữ pháp và từ vựng.<br>\r\nMỗi mô đun trong sách bài tập gồm các dạng bài:<br>\r\n-  Lesson 1 & 2: tập trung luyện tập kĩ năng đọc-viết<br>\r\n-  Lesson 3 & 4 : luyện kĩ năng đọc chuyện<br>\r\n-  Lesson 5, 6, 7: luyện tập ngữ pháp và từ vựng<br>\r\n-  Lesson 8: luyện kĩ năng nghe<br>\r\nKết thúc mỗi mô đun là phần check point.<br>\r\nCuối mỗi cuốn Sách bài tập - Activity book là nội dung Welcome to Asian Countries và Story cutouts và một số các nội dung khác liên quan đến các nội dung văn hoá của thế giới và của nước nói tiếng Anh.', '', NULL, 3),
(10, 'Smiles Special Edition Grade 4 - Activity Book', 'smiles-special-edition-grade-4---activity-book-10', 'S4-AB.png', 1, 4, 'Virginia Evans - Jenny Dooley', 'Hợp tác xuất bản cùng Express Publishing', '2018', 'Smiles Special Edition Grade 4 - Activity Book là sách bổ trợ cho cuốn sách học sinh, được thiết kế với 6 mô đun tương ứng với 6 mô đun trong Sách học sinh, chứa đựng các họat động giao tiếp đa dạng để phát triển 4 kĩ năng nghe, nói, đọc, viết và rèn luyện ngữ pháp và từ vựng. <br>\r\nMỗi mô đun trong sách bài tập gồm các dạng bài: <br>\r\n-  Lesson 1 & 2: tập trung luyện tập kĩ năng đọc-viết <br>\r\n-  Lesson 3 & 4 : luyện kĩ năng đọc chuyện <br>\r\n-  Lesson 5, 6, 7: luyện tập ngữ pháp và từ vựng <br>\r\n-  Lesson 8: luyện kĩ năng nghe <br>\r\nKết thúc mỗi mô đun là phần check point. <br>\r\nCuối mỗi cuốn Sách bài tập - Activity book là nội dung Welcome to Asian Countries và Story cutouts và một số các nội dung khác liên quan đến các nội dung văn hoá của thế giới và của nước nói tiếng Anh.', '', NULL, 3),
(11, 'Smiles Special Edition Grade 4 - Student\'s book', 'smiles-special-edition-grade-4---student\'s-book-11', 'S4-PB.png', 1, 4, 'Virginia Evans - Jenny Dooley', 'Hợp tác xuất bản cùng Express Publishing', '2018', 'Cấu trúc của Smiles Special Edition Grade 4 - Student\'s book bao gồm phần Khởi động (Let’s Start) và 6 mô đun (module) được thiết kế dựa vào chủ đề (theme-based) phù hợp với từng lứa tuổi học sinh. <br>\r\nMỗi mô đun/chủ đề tập trung vào các nội dung ngôn ngữ: từ vựng, cấu trúc câu, ngữ âm và phần mở rộng Project. Sau mỗi module gồm hai phần: Smiles Magazine và Time for CLIL (Content Language Integrated Learning).<br>\r\nSau 6 mô đun là các nội dung giới thiệu về văn hoá, xã hội của các nước trên thế giới và châu Á hay một số nội dung khác trong từng textbook cụ thể.', '', NULL, 3),
(12, 'Smiles Special Edition Grade 3 - Activity Book', 'smiles-special-edition-grade-3---activity-book-12', 'S3-AB.png', 1, 3, 'Virginia Evans - Jenny Dooley', 'Hợp tác xuất bản cùng Express Publishing', '2018', 'Smiles Special Edition Grade 3 - Activity Book là sách bổ trợ cho cuốn sách học sinh, được thiết kế với 6 mô đun tương ứng với 6 mô đun trong Sách học sinh, chứa đựng các họat động giao tiếp đa dạng để phát triển 4 kĩ năng nghe, nói, đọc, viết và rèn luyện ngữ pháp và từ vựng. <br>\r\nMỗi mô đun trong sách bài tập gồm các dạng bài: <br>\r\n-  Lesson 1 & 2: tập trung luyện tập kĩ năng đọc-viết <br>\r\n-  Lesson 3 & 4 : luyện kĩ năng đọc chuyện <br>\r\n-  Lesson 5, 6, 7: luyện tập ngữ pháp và từ vựng <br>\r\n-  Lesson 8: luyện kĩ năng nghe <br>\r\nKết thúc mỗi mô đun là phần check point. <br>\r\nCuối mỗi cuốn Sách bài tập - Activity book là nội dung Welcome to Asian Countries và Story cutouts và một số các nội dung khác liên quan đến các nội dung văn hoá của thế giới và của nước nói tiếng Anh.', '', NULL, 3),
(13, 'Smiles Special Edition Grade 3 - Student\'s book', 'smiles-special-edition-grade-3---student\'s-book-13', 'S3-PB.png', 1, 3, 'Virginia Evans - Jenny Dooley', 'Hợp tác xuất bản cùng Express Publishing', '2018', 'Cấu trúc của Smiles Special Edition Grade 3 - Student\'s book bao gồm phần Khởi động (Let’s Start) và 6 mô đun (module) được thiết kế dựa vào chủ đề (theme-based): Come and play, A nice bed, I can...., It\'s a monster, Time to eat, Every day. <br>\r\nMỗi mô đun/chủ đề tập trung vào các nội dung ngôn ngữ : từ vựng, cấu trúc câu, ngữ âm và phần mở rộng Project. Sau mỗi module gồm hai phần: Smiles Magazine và Time for CLIL (Content Language Integrated Learning). <br>\r\nSau 6 mô đun là các nội dung giới thiệu về văn hoá, xã hội của các nước trên thế giới và châu Á như: Welcome to Asian Countries; My Green Passport và một số nội dung khác trong từng textbook cụ thể.', '', NULL, 3),
(14, 'Smiles Special Edition Grade 2 - Activity Book', 'smiles-special-edition-grade-2---activity-book-14', 'S2-AB.png', 1, 2, 'Virginia Evans - Jenny Dooley', 'Hợp tác xuất bản cùng Express Publishing', '2018', 'Smiles Special Edition Grade 2 - Activity Book là sách bổ trợ cho cuốn sách học sinh, được thiết kế với 6 mô đun tương ứng với 6 mô đun trong Sách học sinh, chứa đựng các họat động giao tiếp đa dạng để phát triển 4 kĩ năng nghe, nói, đọc, viết và rèn luyện ngữ pháp và từ vựng. <br>\r\nMỗi mô đun trong sách bài tập gồm các dạng bài: <br>\r\n-  Lesson 1 & 2: tập trung luyện tập kĩ năng đọc-viết <br>\r\n-  Lesson 3 & 4 : luyện kĩ năng đọc chuyện <br>\r\n-  Lesson 5, 6, 7: luyện tập ngữ pháp và từ vựng <br>\r\n-  Lesson 8: luyện kĩ năng nghe <br>\r\nKết thúc mỗi mô đun là phần check point. <br>\r\nCuối mỗi cuốn Sách bài tập - Activity book là nội dung Welcome to Asian Countries và Story cutouts và một số các nội dung khác liên quan đến các nội dung văn hoá của thế giới và của nước nói tiếng Anh.', '', NULL, 3),
(15, 'Smiles Special Edition Grade 2 - Student\'s book', 'smiles-special-edition-grade-2---student\'s-book-15', 'S2-PB.png', 1, 2, 'Virginia Evans - Jenny Dooley', 'Hợp tác xuất bản cùng Express Publishing', '2018', 'Cấu trúc của Smiles Special Edition Grade 2 - Student\'s book bao gồm phần Khởi động (Let’s Start) và 6 mô đun (module) được thiết kế dựa vào chủ đề (theme-based): My family, My house, My birthday, My Animals, My Toys, My Holiday. <br>\r\nMỗi mô đun/chủ đề tập trung vào các nội dung ngôn ngữ : từ vựng, cấu trúc câu, ngữ âm và phần mở rộng Project. Sau mỗi module gồm hai phần: Smiles Magazine và Time for CLIL (Content Language Integrated Learning). <br>\r\nSau 6 mô đun là các nội dung giới thiệu về văn hoá, xã hội của các nước trên thế giới và châu Á như: Welcome to Asian Countries; My Green Passport và một số nội dung khác trong từng textbook cụ thể.', '', NULL, 3),
(16, 'Smiles Special Edition Grade 1 - Activity Book', 'smiles-special-edition-grade-1---activity-book-16', 'S1-AB.png', 1, 1, 'Virginia Evans - Jenny Dooley', 'Hợp tác xuất bản cùng Express Publishing', '2018', 'Smiles Special Edition Grade 1 - Activity Book là sách bổ trợ cho cuốn sách học sinh, được thiết kế với 6 mô đun tương ứng với 6 mô đun trong Sách học sinh, chứa đựng các họat động giao tiếp đa dạng để phát triển 4 kĩ năng nghe, nói, đọc, viết và rèn luyện ngữ pháp và từ vựng. <br>\r\nMỗi mô đun trong sách bài tập gồm các dạng bài:<br> \r\n-  Lesson 1 & 2: tập trung luyện tập kĩ năng đọc-viết <br>\r\n-  Lesson 3 & 4 : luyện kĩ năng đọc chuyện <br>\r\n-  Lesson 5, 6, 7: luyện tập ngữ pháp và từ vựng <br>\r\n-  Lesson 8: luyện kĩ năng nghe <br>\r\nKết thúc mỗi mô đun là phần check point. <br>\r\nCuối mỗi cuốn Sách bài tập - Activity book là nội dung Welcome to Asian Countries và Story cutouts và một số các nội dung khác liên quan đến các nội dung văn hoá của thế giới và của nước nói tiếng Anh.', '', NULL, 3),
(17, 'Smiles Special Edition Grade 1 - Student\'s book', 'smiles-special-edition-grade-1---student\'s-book-17', 'S1-PB.png', 1, 1, 'Virginia Evans - Jenny Dooley', 'Hợp tác xuất bản cùng Express Publishing', '2018', 'Cấu trúc của Smiles Special Edition Grade 1 - Student\'s book bao gồm phần Khởi động (Let’s Start) và 6 mô đun (module) được thiết kế dựa vào chủ đề (theme-based): My family, My school, My Room, My Pets, My Food, My Music. <br>\r\nMỗi mô đun/chủ đề tập trung vào các nội dung ngôn ngữ : từ vựng, cấu trúc câu, ngữ âm và phần mở rộng Project. Sau mỗi module gồm hai phần: Smiles Magazine và Time for CLIL (Content Language Integrated Learning). <br>\r\nSau 6 mô đun là các nội dung giới thiệu về văn hoá, xã hội của các nước trên thế giới và châu Á như: Welcome to Asian Countries ; My Green Passport và một số nội dung khác trong từng textbook cụ thể.', '', NULL, 3),
(18, 'Nhật kí ngày hè vui môn Tiếng Anh lớp 1', 'nhat-ki-ngay-he-vui-mon-tieng-anh-lop-1-18', 'TA.jpg', 1, 1, 'Nguyễn Thị Kim Oanh – Đỗ Thị Ngọc Hiền', 'GDVN', '2021', 'Sách giúp HS ôn luyện và củng cố kiến thức qua hình thức HỌC MÀ CHƠI, CHƠI MÀ HỌC<br>\r\nHình thức sách hiện đại, HS có thể lấy ra 1 tờ bài học mỗi môn và cho dù ở đâu HS vẫn hoàn thành được nhiệm vụ. Cuối bài có gợi ý check list việc đã làm trong ngày, chia sẻ cảm xúc, giúp HS hình thành thói quen làm việc khoa học <br>\r\nTrong bài ôn tập có những tình huống gợi mở, nhắc lại kiến thức hoặc kết nối với thực tế cuộc sống giúp HS dễ dàng hoàn thành công việc <br>\r\nCuối sách có những sticker làm phần thưởng cho HS chăm ngoan', '', 1, 2),
(19, 'Bài tập bổ trợ và nâng cao tiếng Anh 12', 'bai-tap-bo-tro-va-nang-cao-tieng-anh-12-19', 'Bai tap bo tro va nang cao tieng Anh 12.jpg', 1, 12, 'Nguyễn Thị Chi (Chủ biên), Nguyễn Hữu Cương, Nguyễn Thu Hiền', 'GDVN', '2021', 'Phần bài tập bao gồm các bài luyện đa dạng về ngữ âm, ngữ pháp, từ vựng, đọc hiểu và viết tương ứng theo nội dung các đơn vị bài học của sách giáo khoa Tiếng Anh 10, 11, 12. <br>\r\nChủ đề và nội dung phong phú, hấp dẫn, phù hợp với lứa tuổi HS cấp THPT;\r\nĐảm bảo tính khoa học; <br>\r\nĐảm bảo tính thực tiễn và cập nhật; <br>\r\nGiúp HS củng cố kiến thức đã học, mở rộng và nâng cao kiến thức và kĩ năng ngôn ngữ, và làm quen với các dạng bài thi và kiểm tra; <br>\r\nNội dung gắn với đời sống văn hoá xã hội của Việt Nam và các nước trên thế giới, đặc biệt là các nước nói tiếng Anh.', '', NULL, 2),
(20, 'Bài tập bổ trợ và nâng cao tiếng Anh 11', 'bai-tap-bo-tro-va-nang-cao-tieng-anh-11-20', 'Bai tap bo tro va nang cao tieng Anh 11.jpg', 1, 11, 'Nguyễn Thị Chi (Chủ biên), Nguyễn Hữu Cương, Nguyễn Thu Hiền', 'GDVN', '2021', 'Phần bài tập bao gồm các bài luyện đa dạng về ngữ âm, ngữ pháp, từ vựng, đọc hiểu và viết tương ứng theo nội dung các đơn vị bài học của sách giáo khoa Tiếng Anh 10, 11, 12. <br>\r\nChủ đề và nội dung phong phú, hấp dẫn, phù hợp với lứa tuổi HS cấp THPT; <br>\r\nĐảm bảo tính khoa học; <br>\r\nĐảm bảo tính thực tiễn và cập nhật; <br>\r\nGiúp HS củng cố kiến thức đã học, mở rộng và nâng cao kiến thức và kĩ năng ngôn ngữ, và làm quen với các dạng bài thi và kiểm tra; <br>\r\nNội dung gắn với đời sống văn hoá xã hội của Việt Nam và các nước trên thế giới, đặc biệt là các nước nói tiếng Anh', '', NULL, 2),
(21, 'Bài tập bổ trợ và nâng cao tiếng Anh 10', 'bai-tap-bo-tro-va-nang-cao-tieng-anh-10-21', 'Bai tap bo tro va nang cao tieng Anh 10.jpg', 1, 10, 'Nguyễn Thị Chi (Chủ biên), Nguyễn Hữu Cương, Nguyễn Thu Hiền', 'GDVN', '2021', 'Phần bài tập bao gồm các bài luyện đa dạng về ngữ âm, ngữ pháp, từ vựng, đọc hiểu và viết tương ứng theo nội dung các đơn vị bài học của sách giáo khoa Tiếng Anh 10, 11, 12. <br>\r\nChủ đề và nội dung phong phú, hấp dẫn, phù hợp với lứa tuổi HS cấp THPT; <br>\r\nĐảm bảo tính khoa học; <br>\r\nĐảm bảo tính thực tiễn và cập nhật; <br>\r\nGiúp HS củng cố kiến thức đã học, mở rộng và nâng cao kiến thức và kĩ năng ngôn ngữ, và làm quen với các dạng bài thi và kiểm tra; <br>\r\nNội dung gắn với đời sống văn hoá xã hội của Việt Nam và các nước trên thế giới, đặc biệt là các nước nói tiếng Anh', '', NULL, 2),
(22, 'Vở bài tập tiếng Anh 6', 'vo-bai-tap-tieng-anh-6-22', 'Vo bai tap tieng Anh 6.jpg', 1, 6, 'Lương Quỳnh Trang - Quang Thị Hoàn - Nguyễn Thị Kim Phượng', 'GDVN', '2021', 'Cuốn sách Vở bài tập Tiếng Anh 6 được biên soạn nhằm giúp cho giáo viên và học sinh có thêm tài liệu tham khảo để ôn tập, củng cố và bổ trợ nâng cao kiến thức cũng như kĩ năng sử dụng tiếng Anh. <br>\r\nCuốn sách được xây dựng dựa trên nền tảng chương trình sách giáo khoa của Bộ Giáo dục và Đào tạo, có cấu trúc gồm: <br>\r\nPhần 1: Ôn tập kiến thức, mở rộng kĩ năng theo 10 chủ đề trong chương trình học.\r\nPhần 2: Đề kiểm tra tổng hợp giúp học sinh củng cố kiến thức, rèn luyện kĩ năng làm bài. <br>\r\nPhần 3: Đáp án.', '', NULL, 2),
(23, 'Bài tập bổ trợ và nâng cao tiếng Anh 2', 'bai-tap-bo-tro-va-nang-cao-tieng-anh-2-23', 'Bo tro va nang cao tieng Anh 2.jpg', 1, 2, 'Lương Quỳnh Trang - Trần Thị Lan Anh - Trần Nguyễn Phương Thùy - Nguyễn Thị Thanh Xuân', 'GDVN', '2021', 'Biên soạn bám sát các chủ đề trong chương trình GDPT môn tiếng Anh <br>\r\nGiúp HS ôn tập nâng cao kiến thức và kĩ năng ngôn ngữ  <br>\r\nTích hợp các kiến thức liên môn (CLIL) trong các hoạt động học tập <br>\r\nLà tài liệu ôn tập kiến thức chuẩn bị cho các kì thi và kiểm tra đánh giá', '', NULL, 2),
(24, 'Bài tập bổ trợ và nâng cao tiếng Anh 1', 'bai-tap-bo-tro-va-nang-cao-tieng-anh-1-24', 'Bo tro va nang cao tieng Anh 1.jpg', 1, 1, 'Lương Quỳnh Trang - Trần Thị Lan Anh - Trần Nguyễn Phương Thùy - Nguyễn Thị Thanh Xuân', 'GDVN', '2021', 'Biên soạn bám sát các chủ đề trong chương trình GDPT môn tiếng Anh <br>\r\nGiúp HS ôn tập nâng cao kiến thức và kĩ năng ngôn ngữ <br>\r\nTích hợp các kiến thức liên môn (CLIL) trong các hoạt động học tập <br>\r\nLà tài liệu ôn tập kiến thức chuẩn bị cho các kì thi và kiểm tra đánh giá', '', NULL, 2),
(25, 'Writing - Vở tập viết tiếng Anh 2', 'writing---vo-tap-viet-tieng-anh-2-25', 'Vo tap viet tieng Anh 2.jpg', 1, 2, 'An Thị Thu Hà - Trần Nguyễn Phương  Thùy', 'GDVN', '2021', 'Cuốn sách là một trong những tài liệu dạy và học cần thiết cho môn Tiếng Anh, giúp học sinh luyện tập viết chữ theo đúng phong cách tiếng Anh. Với cuốn sách này, học sinh được thực hành các bài tập phong phú, đa dạng như: Tô hoặc chép lại chữ cái trong từ, Viết chữ cái trong từ, Viết từ đơn lẻ, Viết từ trong câu… Nhờ vậy, các em vừa có thể ôn luyện và ghi nhớ các từ vựng, mẫu câu đã được học trong sách giáo khoa, vừa luyện chính tả và dần hình thành kĩ năng Viết để hỗ trợ tốt hơn cho các bậc học tiếp theo.', '', NULL, 2),
(26, 'Writing - Vở tập viết tiếng Anh 1', 'writing---vo-tap-viet-tieng-anh-1-26', 'Vo tap viet tieng Anh 1-1.jpg', 1, 1, 'An Thị Thu Hà - Trần Nguyễn Phương Thùy', 'GDVN', '2021', 'Cuốn sách là một trong những tài liệu dạy và học cần thiết cho môn Tiếng Anh, giúp học sinh luyện tập viết chữ theo đúng phong cách tiếng Anh. Với cuốn sách này, học sinh được thực hành các bài tập phong phú, đa dạng như: Tô hoặc chép lại chữ cái trong từ, Viết chữ cái trong từ, Viết từ đơn lẻ, Viết từ trong câu… Nhờ vậy, các em vừa có thể ôn luyện và ghi nhớ các từ vựng, mẫu câu đã được học trong sách giáo khoa, vừa luyện chính tả và dần hình thành kĩ năng Viết để hỗ trợ tốt hơn cho các bậc học tiếp theo.', '', NULL, 2),
(27, 'Tiếng Anh 1', 'tieng-anh-1-27', 'Bia-Tieng-Anh-1-SHS.png', 1, 1, 'Hoàng Văn Vân (Tổng Chủ biên), Nguyễn Quốc Tuấn (Chủ biên),…', 'GDVN', '2020', 'Tiếng Anh 1 – Sách học sinh được biên soạn theo Chương trình giáo dục phổ thông – Làm quen tiếng Anh lớp 1 và lớp 2 của Bộ Giáo dục và Đào tạo. Cuốn sách giúp học sinh lớp 1 bước đầu làm quen và có nhận thức đơn giản nhất về tiếng Anh, làm tiền đề cho việc hình thành và phát triển năng lực tiếng Anh ở các lớp học sau. Tiếng Anh 1 – Sách học sinh được biên soạn theo một số quan điểm sau:\r\n• Lấy định hướng giao tiếp (Communicative approach) làm cơ sở biên soạn sách giáo khoa và các học liệu học tập. Theo đó, Tiếng Anh 1 – Sách học sinh giúp các em làm quen và rèn luyện các kĩ năng giao tiếp nghe, nói, đọc, viết (đặc biệt nhấn mạnh hai kĩ năng nghe và nói). Hệ thống âm, từ vựng, cấu trúc rất đơn giản và cơ bản của tiếng Anh là phương tiện hình thành các kĩ năng giao tiếp.\r\n• Coi hoạt động học của học sinh (Learning-centred approach) là trọng tâm của quá trình dạy học.\r\n• Lấy hoạt động học qua chơi, chơi để học làm phương thức cơ bản trong làm quen và học tiếng Anh với đối tượng học sinh nhỏ tuổi.\r\nTiếng Anh 1, Sách học sinh gồm 16 đơn vị bài học (Unit); mỗi đơn vị bài học có 3 bài học (Lesson). Xen kẽ các đơn vị bài học là 4 bài Fun time. Bốn bài Review (bao gồm phần Story và Self-check) được đặt sau mỗi bốn đơn vị bài học giúp học sinh ôn tập, củng cố kiến thức, kĩ năng và tự kiểm tra, đánh giá kết quả học tập của mình. Mỗi đơn vị bài học được thiết kế thành 8 hoạt động chính:\r\n1. Listen and repeat: Làm quen với âm và từ cơ bản trong chủ đề thông qua các ngữ cảnh giao tiếp.\r\n2. Point and say: Luyện âm và từ chứa âm trong tình huống giao tiếp.\r\n3. Listent and chant: Giúp nghe và luyện tập, vận dụng âm và từ chứa âm trong các cụm từ hoặc câu đơn giản qua các bài Chant.\r\n4. Listen and tick: Luyện nghe âm trong từ, từ chứa âm trong câu.\r\n5. Look and trace/ Look, trace and write: Tập tô các con chữ (chữ hoa và chữ thường) và điền các con chữ còn thiếu vào các từ.\r\n6. Listen and repeat: Nghe và nhắc lại các cấu trúc câu, các hội thoại đơn giản.\r\n7. Let’s talk: Tập nói các câu và các hội thoại đơn giản qua các tình huống giao tiếp.\r\n8. Let’s sing: Ôn tập, củng cố các âm, từ vựng, cấu trúc câu đã học thông qua bài hát.\r\n', '#', NULL, 1),
(28, 'Tiếng Anh 1', 'tieng-anh-1-28', 'Bia---Tieng-Anh-1---SBT.png', 1, 1, 'Hoàng Văn Vân (Tổng Chủ biên), Nguyễn Quốc Tuấn (Chủ biên),…', 'GDVN', '2020', 'Tiếng Anh 1, Sách bài tập được biên soạn theo phương pháp dạy học tiếng Anh hiện đại, với sự hợp tác về chuyên môn và kĩ thuật giữa NXB Giáo dục Việt Nam và NXB Macmillan Education. Sách gồm 16 đơn vị bài tập, bám sát 16 đơn vị bài học trong sách học sinh. Mỗi đơn vị bài tập có các nội dung như sau:\r\n1. Look and match: Ôn lại và nhận biết nghĩa của các từ cơ bản thông qua các tranh.\r\n2. Listen and circle/Listen and number: Luyện nghe hiểu trong các tình huống giao tiếp.\r\n3. Look and write: Luyện cách viết các con chữ cơ bản.\r\n4. Look and write. Then say: Luyện cách viết các con chữ trong các từ cơ bản và đọc được các từ đó.\r\n5. Read and match/circle/tick: Củng cố và phát triển kĩ năng đọc hiểu các câu đơn giản.\r\n6. Game: Củng cố vốn từ vựng, phát triển các kĩ năng đọc và nói thông qua các hoạt động, trò chơi sáng tạo và vui nhộn.\r\n7. Project: Là một “Dự án” đơn giản, giúp học sinh ôn lại các từ đã học thông qua các hoạt động để phát huy tính chủ động, sáng tạo, cá nhân hoá trong các tình huống thực tế.\r\n', '#', NULL, 1),
(29, 'Tiếng Anh 1', 'tieng-anh-1-29', 'Bia-1-4-Tieng-Anh-1-SGV.png', 1, 1, 'Hoàng Văn Vân (Tổng Chủ biên), Nguyễn Quốc Tuấn (Chủ biên),…', 'GDVN', '2020', 'Tiếng Anh 1, Sách giáo viên nằm trong bộ sách Tiếng Anh 1, 2 của NXBGDVN hợp tác với NXB Macmillan (MPC) biên soạn theo chương trình tiếng Anh 1, 2 đã được Bộ Giáo dục và Đào tạo ban hành vào tháng 1/2018. Cuốn sách giúp giáo viên nắm vững mục tiêu, nội dung, phương pháp và kĩ thuật giảng dạy tiếng Anh ở lớp 1.', '#', NULL, 1),
(30, 'Tiếng Anh 3', 'tieng-anh-3-30', 'Bia-TA3_SHS_1.png', 1, 3, 'Hoàng Văn Vân (Tổng Chủ biên), Nguyễn Quốc Tuấn (Chủ biên),…', 'GDVN', '2020', 'Tiếng Anh 3, Tập 1 do Nhà  xuất bản Giáo dục Việt Nam tổ  chức biên soạn theo Chương trình thí điểm Tiếng Anh tiểu học do Bộ  Giáo dục và  Đào tạo ban hành, với sự hợp tác chặt chẽ về chuyên môn và  kĩ thuật của Nhà  xuất bản Macmillan (MPC). Sách được biên soạn theo đường hướng giao tiếp, giúp học sinh bước đầu hình thành và  phát triển năng lực giao tiếp bằng tiếng Anh, thông qua bốn kĩ năng nghe, nói, đọc và  viết, trong đó ưu tiên phát triển hai kĩ năng nghe và  nói. \r\nTiếng Anh 3, Tập Một xoay quanh hai chủ điểm giao tiếp gần gũi với học sinh: Me and My Friends, Me and My School. Mỗi chủ điểm được chia thành năm đơn vị  bài học (Unit) tương ứng với năm chủ đề của chương trình. Sau năm đơn vị bài học là  một bài ôn (Review) tập trung vào các kĩ năng giao tiếp (nghe, nói, đọc, viết) và  kiến thức ngôn ngữ cơ bản (ngữ âm, từ  vựng, ngữ pháp).\r\nTiếng Anh 3, Tập Một được biên soạn dựa trên những cơ sở lí luận và thực tiễn của việc dạy và  học tiếng Anh tiểu học ở Việt Nam, có tính đến tâm lí lứa tuổi và giao lưu quốc tế.', '#', 1, 1),
(31, 'Tiếng Anh 3', 'tieng-anh-3-31', 'Bia-TA3_SHS_2.png', 1, 3, 'Hoàng Văn Vân (Tổng Chủ biên), Nguyễn Quốc Tuấn (Chủ biên),…', 'GDVN', '2020', 'Tiếng Anh 3, Tập Hai do Nhà  xuất bản Giáo dục Việt Nam tổ  chức biên soạn theo Chương trình thí điểm Tiếng Anh tiểu học do Bộ  Giáo dục và  Đào tạo ban hành, với sự hợp tác chặt chẽ về chuyên môn và  kĩ thuật của Nhà  xuất bản Macmillan (MPC). Sách được biên soạn theo đường hướng giao tiếp, giúp học sinh bước đầu hình thành và  phát triển năng lực giao tiếp bằng tiếng Anh, thông qua bốn kĩ năng nghe, nói, đọc và  viết, trong đó ưu tiên phát triển hai kĩ năng nghe và  nói.\r\nTiếng Anh 3, Tập Hai xoay quanh hai chủ điểm giao tiếp gần gũi với học sinh: Me and My Family, Me and the World Around. Mỗi chủ điểm được chia thành năm đơn vị  bài học (Unit) tương ứng với năm chủ đề của chương trình. Sau năm đơn vị bài học là  một bài ôn (Review) tập trung vào các kĩ năng giao tiếp (nghe, nói, đọc, viết) và  kiến thức ngôn ngữ cơ bản (ngữ âm, từ  vựng, ngữ pháp). \r\nTiếng Anh 3, Tập Hai được biên soạn dựa trên những cơ sở lí luận và thực tiễn của việc dạy và  học tiếng Anh tiểu học ở Việt Nam, có tính đến tâm lí lứa tuổi và giao lưu quốc tế. \r\n', '#', 2, 1),
(32, 'Sách bài tập Tiếng Anh 3', 'sach-bai-tap-tieng-anh-3-32', 'Bia-TA3_SBT.png', 1, 3, 'Hoàng Văn Vân (Tổng Chủ biên), Nguyễn Quốc Tuấn (Chủ biên),…', 'GDVN', '2020', 'Tiếng Anh 3 Sách Bài Tập được biên soạn giúp học sinh củng cố, mở rộng kiến thức ngôn ngữ và kĩ năng giao tiếp tiếng Anh, đồng thời cung cấp thêm nguồn tư liệu dạy học cho giáo viên và phụ huynh sử dụng ngoài sách học sinh và sách giáo viên chính khóa để dạy thêm cho học sinh và con mình. Sách gồm 20 đơn vị bài tập tương ứng với 20 bài học trong sách học sinh. Cuối sách có phần đáp án để học sinh tự kiểm tra lại bài đã làm. Mỗi đơn vị bài tập gồm các phần sau đây:\r\nA.	PHONICS AND VOCABULARY\r\nB.	SENTENCES PATTERNS\r\nC.	SPEAKING\r\nD.	READING\r\nE.	WRITING \r\n', '#', NULL, 1),
(33, 'Tiếng Anh 4', 'tieng-anh-4-33', 'Bia-TA4_SHS_1.png', 1, 4, 'Hoàng Văn Vân (Tổng Chủ biên), Nguyễn Quốc Tuấn (Chủ biên),…', 'GDVN', '2020', 'Tiếng Anh 4, Tập Một do Nhà  xuất bản Giáo dục Việt Nam tổ  chức biên soạn theo Chương trình thí điểm Tiếng Anh tiểu học do Bộ  Giáo dục và  Đào tạo ban hành, với sự hợp tác chặt chẽ về chuyên môn và  kĩ thuật của Nhà  xuất bản Macmillan (MPC). Sách được biên soạn theo đường hướng giao tiếp, giúp học sinh bước đầu hình thành và  phát triển năng lực giao tiếp bằng tiếng Anh, thông qua bốn kĩ năng nghe, nói, đọc và  viết, trong đó ưu tiên phát triển hai kĩ năng nghe và  nói. \r\nTiếng Anh 4, Tập Một xoay quanh hai chủ điểm giao tiếp gần gũi với học sinh: Me and My Friends, Me and My School. Mỗi chủ điểm được chia thành năm đơn vị  bài học (Unit) tương ứng với năm chủ đề của chương trình. Sau năm đơn vị bài học là  một bài ôn (Review) tập trung vào ôn tập và củng cố các kĩ năng giao tiếp (nghe, nói, đọc, viết) và  kiến thức ngôn ngữ cơ bản (ngữ âm, từ  vựng, ngữ pháp). \r\nTiếng Anh 4, Tập Một được biên soạn dựa trên những cơ sở lí luận và thực tiễn của việc dạy và  học tiếng Anh tiểu học ở Việt Nam, có tính đến tâm lí lứa tuổi và giao lưu quốc tế. \r\n', '#', 1, 1),
(34, 'Tiếng Anh 4', 'tieng-anh-4-34', 'Bia-TA4_SHS_2.png', 1, 4, 'Hoàng Văn Vân (Tổng Chủ biên), Nguyễn Quốc Tuấn (Chủ biên),…', 'GDVN', '2020', 'Tiếng Anh 4, Tập Hai do Nhà  xuất bản Giáo dục Việt Nam tổ  chức biên soạn theo Chương trình thí điểm Tiếng Anh tiểu học do Bộ  Giáo dục và  Đào tạo ban hành, với sự hợp tác chặt chẽ về chuyên môn và  kĩ thuật của Nhà  xuất bản Macmillan (MPC). Sách được biên soạn theo đường hướng giao tiếp, giúp học sinh bước đầu hình thành và  phát triển năng lực giao tiếp bằng tiếng Anh, thông qua bốn kĩ năng nghe, nói, đọc và  viết, trong đó ưu tiên phát triển hai kĩ năng nghe và  nói. \r\nTiếng Anh 4, Tập Hai xoay quanh hai chủ điểm giao tiếp gần gũi với học sinh: Me and My Family, Me and the World Around. Mỗi chủ điểm được chia thành năm đơn vị  bài học (Unit) tương ứng với năm chủ đề của chương trình. Sau năm đơn vị bài học là  một bài ôn (Review) tập trung vào ôn tập và củng cố các kĩ năng giao tiếp (nghe, nói, đọc, viế t) và  kiến thức ngôn ngữ cơ bản (ngữ âm, từ  vựng, ngữ pháp). \r\nTiếng Anh 4, Tập Hai được biên soạn dựa trên những cơ sở lí luận và thực tiễn của việc dạy và  học tiếng Anh tiểu học ở Việt Nam, có tính đến tâm lí lứa tuổi và giao lưu quốc tế. \r\n', '#', 2, 1),
(35, 'Sách bài tập Tiếng Anh 4', 'sach-bai-tap-tieng-anh-4-35', 'Bia-TA4_SBT.png', 1, 4, 'Hoàng Văn Vân (Tổng Chủ biên), Nguyễn Quốc Tuấn (Chủ biên),…', 'GDVN', '2020', 'Tiếng Anh 4 Sách Bài Tập được biên soạn giúp học sinh củng cố, mở rộng kiến thức ngôn ngữ và kĩ năng giao tiếp tiếng Anh, đồng thời cung cấp thêm nguồn tư liệu dạy học cho giáo viên và phụ huynh sử dụng ngoài sách học sinh và sách giáo viên chính khóa để dạy thêm cho học sinh và con mình. Sách gồm 20 đơn vị bài tập tương ứng với 20 bài học trong sách học sinh. Cuối sách có phần đáp án để học sinh tự kiểm tra lại bài đã làm. Mỗi đơn vị bài tập gồm các phần sau đây:\r\nA.	PHONICS\r\nB.	VOCABULARY\r\nC.	SENTENCE PATTERNS\r\nD.	SPEAKING\r\nE.	READING\r\nF.	WRITING\r\n', '#', NULL, 1),
(36, 'Tiếng Anh 5', 'tieng-anh-5-36', 'Bia-TA5_SHS_1.png', 1, 5, 'Hoàng Văn Vân (Tổng Chủ biên), Nguyễn Quốc Tuấn (Chủ biên),…', 'GDVN', '2020', 'Tiếng Anh 5, Tập Một do Nhà xuất bản Giáo dục Việt Nam tổ chức biên soạn theo Chương trình thí điểm Tiếng Anh tiểu học do Bộ Giáo dục và Đào tạo ban hành, với sự hợp tác chặt chẽ về chuyên môn và kĩ thuật của Nhà xuất bản Macmillan (MPC). Sách được biên soạn theo đường hướng giao tiếp, giúp học sinh bước đầu hình thành và phát triển năng lực giao tiếp bằng tiếng Anh, thông qua bốn kĩ năng nghe, nói, đọc và viết, trong đó ưu tiên phát triển hai kĩ năng nghe và nói. \r\nTiếng Anh 5, Tập Một xoay quanh hai chủ điểm giao tiếp gần gũi với học sinh: Me and My Friends, Me and My School. Mỗi chủ điểm được chia thành năm đơn vị bài học (Unit) tương ứng với năm chủ đề của chương trình. Sau năm đơn vị bài học là một bài ôn (Review) tập trung vào ôn tập và củng cố các kĩ năng giao tiếp (nghe, nói, đọc, viết) và kiến thức ngôn ngữ cơ bản (ngữ âm, từ vựng, ngữ pháp). \r\nTiếng Anh 5, Tập Một được biên soạn dựa trên những cơ sở lí luận và thực tiễn của việc dạy và học tiếng Anh tiểu học ở Việt Nam, có tính đến tâm lí lứa tuổi và giao lưu quốc tế. \r\n', '#', 1, 1),
(37, 'Tiếng Anh 5', 'tieng-anh-5-37', 'Bia-TA5_SHS_2.png', 1, 5, 'Hoàng Văn Vân (Tổng Chủ biên), Nguyễn Quốc Tuấn (Chủ biên),…', 'GDVN', '2020', 'Tiếng Anh 5, Tập Hai do Nhà xuất bản Giáo dục Việt Nam tổ chức biên soạn theo Chương trình thí điểm Tiếng Anh tiểu học do Bộ Giáo dục và Đào tạo ban hành, với sự hợp tác chặt chẽ về chuyên môn và kĩ thuật của Nhà xuất bản Macmillan (MPC). Sách được biên soạn theo đường hướng giao tiếp, giúp học sinh bước đầu hình thành và phát triển năng lực giao tiếp bằng tiếng Anh, thông qua bốn kĩ năng nghe, nói, đọc và viết, trong đó ưu tiên phát triển hai kĩ năng nghe và nói. \r\nTiếng Anh 5, Tập Hai xoay quanh hai chủ điểm giao tiếp gần gũi với học sinh: Me and My Family, Me and the World Around. Mỗi chủ điểm được chia thành năm đơn vị bài học (Unit) tương ứng với năm chủ đề của chương trình. Sau năm đơn vị bài học là một bài ôn (Review) tập trung vào ôn tập và củng cố các kĩ năng giao tiếp (nghe, nói, đọc, viết) và kiến thức ngôn ngữ cơ bản (ngữ âm, từ vựng, ngữ pháp). \r\nTiếng Anh 5, Tập Hai được biên soạn dựa trên những cơ sở lí luận và thực tiễn của việc dạy và học tiếng Anh tiểu học ở Việt Nam, có tính đến tâm lí lứa tuổi và giao lưu quốc tế. \r\n', '#', 2, 1),
(38, 'Sách bài tập Tiếng Anh 5', 'sach-bai-tap-tieng-anh-5-38', 'Bia-TA5_SBT.png', 1, 5, 'Hoàng Văn Vân (Tổng Chủ biên), Nguyễn Quốc Tuấn (Chủ biên),…', 'GDVN', '2020', 'Tiếng Anh 5 SÁCH BÀI TẬP được biên soạn giúp học sinh củng cố, mở rộng kiến thức ngôn ngữ và kĩ năng giao tiếp tiếng Anh, đồng thời cung cấp thêm nguồn tư liệu dạy học cho giáo viên và phụ huynh sử dụng ngoài sách học sinh và sách giáo viên chính khoá để dạy thêm cho học sinh và con mình. Sách gồm 20 đơn vị bài tập tương ứng với 20 bài học trong sách học sinh. Cuối sách có phần đáp án để học sinh tự kiểm tra lại bài đã làm. Mỗi đơn vị bài tập gồm các phần sau đây: \r\nA.	PRONUNCIATION\r\nB.	VOCABULARY\r\nC.	SENTENCE PATTERNS\r\nD.	SPEAKING\r\nE.	READING\r\nF.	WRITING\r\n', '#', 0, 1),
(39, 'Tiếng Anh 7', 'tieng-anh-7-39', 'Bia-TA7-SHS-1.png', 1, 7, 'Hoàng Văn Vân (Tổng Chủ biên), Nguyễn Quốc Tuấn (Chủ biên),…', 'GDVN', '2020', 'Tiếng Anh 7, Tập Một được Nhà xuất bản Giáo dục Việt Nam tổ chức biên soạn theo Chương trình Giáo dục phổ thông môn Tiếng Anh thí điểm cấp Trung học cơ sở do Bộ Giáo dục và Đào tạo ban hành theo Quyết định số 01/QĐ-BGDĐT ngày 03 tháng 01 năm 2012, tiếp theo Tiếng Anh 6. Sách được biên soạn theo đường hướng giao tiếp, giúp học sinh sử dụng ngữ liệu (ngữ âm, từ vựng, ngữ pháp) để phát triển năng lực giao tiếp bằng tiếng Anh thông qua bốn kĩ năng nghe, nói, đọc và viết, trong đó, ưu tiên phát triển hai kĩ năng nghe và nói. Trong Tiếng Anh 7, Tập Một, việc học là trung tâm, học sinh là chủ thể của quá trình dạy học, trong đó tâm lí lứa tuổi của học sinh Trung học cơ sở, các đặc điểm văn hoá của Việt Nam và của các nước trên thế giới, đặc biệt là của các nước nói tiếng Anh, được coi trọng.\r\nTiếng Anh 7, Tập một được biên soạn xoay quanh hai chủ điểm (Theme) gần gũi với học sinh: Our Communities và Our Heritage. Mỗi chủ điểm được chia thành ba đơn vị bài học (Unit) tương ứng với ba chủ đề (Topic) của chương trình. Sau mỗi chủ điểm là một bài ôn (Review) tập trung vào kiến thức ngôn ngữ và kĩ năng ngôn ngữ học sinh đã được học và rèn luyện.\r\nTiếng Anh 7, Tập một được biên soạn trên cơ sở những kinh nghiệm thực tiễn của việc dạy tiếng Anh Trung học cơ sở ở Việt Nam với sự hợp tác chặt chẽ về chuyên môn và kĩ thuật của Tập đoàn Xuất bản Giáo dục Pearson.\r\n', '#', 1, 1),
(40, 'Tiếng Anh 7', 'tieng-anh-7-40', 'Bia-TA7-SHS-2.png', 1, 7, 'Hoàng Văn Vân (Tổng Chủ biên), Nguyễn Quốc Tuấn (Chủ biên),…', 'GDVN', '2020', 'Tiếng Anh 7, Tập Hai được Nhà xuất bản Giáo dục Việt Nam tổ chức biên soạn theo Chương trình Giáo dục phổ thông môn Tiếng Anh thí điểm cấp Trung học cơ sở do Bộ Giáo dục và Đào tạo ban hành theo Quyết định số 01/QĐ-BGDĐT ngày 03 tháng 01 năm 2012, tiếp theo Tiếng Anh 6. Sách được biên soạn theo đường hướng giao tiếp, giúp học sinh sử dụng ngữ liệu (ngữ âm, từ vựng, ngữ pháp) để phát triển năng lực giao tiếp bằng tiếng Anh thông qua bốn kĩ năng nghe, nói, đọc và viết, trong đó, ưu tiên phát triển hai kĩ năng nghe và nói. Trong Tiếng Anh 7, Tập Hai, việc học là trung tâm, học sinh là chủ thể của quá trình dạy học, trong đó tâm lí lứa tuổi của học sinh Trung học cơ sở, các đặc điểm văn hoá của Việt Nam và của các nước trên thế giới, đặc biệt là của các nước nói tiếng Anh, được đặc biệt coi trọng.\r\nTiếng Anh 7, Tập Hai được biên soạn xoay quanh hai chủ điểm (Theme) gần gũi với học sinh: Our World và Visions of the Future. Mỗi chủ điểm được chia thành ba đơn vị bài học (Unit) tương ứng với ba chủ đề (Topic) của chương trình. Sau mỗi chủ điểm là một bài ôn (Review) tập trung vào kiến thức ngôn ngữ và kĩ năng ngôn ngữ học sinh đã được học và rèn luyện.\r\nTiếng Anh 7, Tập Hai được biên soạn trên cơ sở những kinh nghiệm thực tiễn của việc dạy tiếng Anh  Trung học cơ sở ở Việt Nam với sự hợp tác chặt chẽ về chuyên môn và kĩ thuật của Tập đoàn Xuất bản Giáo dục Pearson.\r\n', '#', 2, 1),
(41, 'Sách bài tập Tiếng Anh 7', 'sach-bai-tap-tieng-anh-7-41', 'Bia-TA7-SBT-1.png', 1, 7, 'Hoàng Văn Vân (Tổng Chủ biên), Nguyễn Quốc Tuấn (Chủ biên),…', 'GDVN', '2020', 'TIẾNG ANH 7 – SÁCH BÀI TẬP (TẬP MỘT) được biên soạn để giúp học sinh củng cố và mở rộng kiến thức ngôn ngữ và kĩ năng giao tiếp tiếng Anh các em đã học trong Tiếng Anh 7 – Sách học sinh (Tập Một). Sách gồm 6 đơn vị bài tập ứng với 6 đơn vị bài học trong Tiếng Anh 7 – Sách học sinh và 2 bài tự kiểm tra (Test yourself ). \r\nMỖI ĐƠN VỊ BÀI TẬP GỒM 5 PHẦN:\r\n-	PHONETICS\r\n-	VOCABULARY & GRAMMAR\r\n-	SPEAKING\r\n-	READING\r\n-	WRITING\r\nTEST YOURSELF 1 và TEST YOURSELF 2 giúp học sinh tự kiểm tra những nội dung kiến thức và những yêu cầu về kĩ năng các em đã học sau mỗi 3 đơn vị bài học, đồng thời làm quen với các dạng bài kiểm tra tiếng Anh theo chuẩn quốc tế.\r\nCác bài tập trong Tiếng Anh 7 – Sách bài tập (Tập Một) đa dạng, phong phú, bám sát ngữ pháp, từ vựng và chủ đề trong Tiếng Anh 7 – Sách học sinh. Sách có nhiều tranh minh hoạ sinh động nhằm hỗ trợ học sinh liên hệ hình ảnh với từ ngữ và tình huống trong khi làm bài tập và thực hành giao tiếp.\r\n', '#', 1, 1),
(42, 'Sách bài tập Tiếng Anh 7', 'sach-bai-tap-tieng-anh-7-42', 'Bia-TA7-SBT-2.png', 1, 7, 'Hoàng Văn Vân (Tổng Chủ biên), Nguyễn Quốc Tuấn (Chủ biên),…', 'GDVN', '2020', 'TIẾNG ANH 7 – SÁCH BÀI TẬP (TẬP HAI) được biên soạn để giúp học sinh củng cố và mở rộng kiến thức ngôn ngữ và kĩ năng giao tiếp tiếng Anh các em đã học trong Tiếng Anh 7 – Sách học sinh (Tập Hai). Sách gồm 6 đơn vị bài tập ứng với 6 đơn vị bài học trong Tiếng Anh 7 – Sách học sinh (Tập Hai) và 2 bài tự kiểm tra (Test yourself ). \r\nMỖI ĐƠN VỊ BÀI TẬP GỒM 5 PHẦN:\r\n-	PHONETICS\r\n-	VOCABULARY & GRAMMAR\r\n-	SPEAKING\r\n-	READING\r\n-	WRITING\r\nTEST YOURSELF 3 và TEST YOURSELF 4 giúp học sinh tự kiểm tra những nội dung kiến thức và những yêu cầu về kĩ năng các em đã học sau mỗi 3 đơn vị bài học, đồng thời làm quen với các dạng bài kiểm tra tiếng Anh theo chuẩn quốc tế.\r\nCác bài tập trong Tiếng Anh 7 – Sách bài tập (Tập Hai) đa dạng, phong phú, bám sát ngữ pháp, từ vựng và chủ đề trong Tiếng Anh 7 – Sách học sinh (Tập Hai). Sách có nhiều tranh minh hoạ sinh động nhằm hỗ trợ học sinh liên hệ hình ảnh với từ ngữ và tình huống trong khi làm bài tập và thực hành giao tiếp.\r\n', '#', 2, 1),
(43, 'Tiếng Anh 8', 'tieng-anh-8-43', 'Bia-TA8-SHS-1.png', 1, 8, 'Hoàng Văn Vân (Tổng Chủ biên), Nguyễn Quốc Tuấn (Chủ biên),…', 'GDVN', '2020', 'Tiếng Anh 8, Tập Một được Nhà xuất bản Giáo dục Việt Nam tổ chức biên soạn theo Chương trình Giáo dục phổ thông môn Tiếng Anh thí điểm cấp Trung học cơ sở do Bộ Giáo dục và Đào tạo ban hành theo Quyết định số 01/QĐ-BGDĐT ngày 03 tháng 01 năm 2012, tiếp theo Tiếng Anh 7. Sách được biên soạn theo đường hướng giao tiếp, giúp học sinh sử dụng ngữ liệu (ngữ âm, từ vựng, ngữ pháp) để phát triển năng lực giao tiếp bằng tiếng Anh thông qua bốn kĩ năng nghe, nói, đọc và viết, trong đó, ưu tiên phát triển hai kĩ năng nghe và nói. Trong Tiếng Anh 8, Tập Một, việc học là trung tâm, học sinh là chủ thể của quá trình dạy học, trong đó tâm lí lứa tuổi của học sinh Trung học cơ sở, các đặc điểm văn hóa của Việt Nam và của các nước trên thế giới, đặc biệt là của các nước nói tiếng Anh, được đặc biệt coi trọng.\r\nTiếng Anh 8, Tập Một được biên soạn xoay quanh hai chủ điểm (Theme) gần gũi với học sinh: Our Communities và Our Heritage. Mỗi chủ điểm được chia thành ba đơn vị bài học (Unit) tương ứng với ba chủ đề (Topic) của Chương trình. Sau mỗi chủ điểm là một bài ôn (Review) tập trung vào kiến thức ngôn ngữ và kĩ năng ngôn ngữ học sinh đã được học và rèn luyện.\r\nTiếng Anh 8, Tập Một được biên soạn trên cơ sở những kinh nghiệm thực tiễn của việc dạy tiếng Anh  Trung học cơ sở ở Việt Nam với sự hợp tác chặt chẽ về chuyên môn và kĩ thuật của Tập đoàn Xuất bản Giáo dục Pearson.\r\n', '#', 1, 1);
INSERT INTO `book` (`id`, `name`, `slug`, `img`, `type`, `class`, `author`, `publishing`, `year`, `description`, `link`, `part`, `idcate`) VALUES
(44, 'Tiếng Anh 8', 'tieng-anh-8-44', 'Bia-TA8-SHS-2.png', 1, 8, 'Hoàng Văn Vân (Tổng Chủ biên), Nguyễn Quốc Tuấn (Chủ biên),…', 'GDVN', '2020', 'Tiếng Anh 8, Tập Hai được Nhà xuất bản Giáo dục Việt Nam tổ chức biên soạn theo Chương trình Giáo dục phổ thông môn Tiếng Anh thí điểm cấp Trung học cơ sở do Bộ Giáo dục và Đào tạo ban hành theo Quyết định số 01/QĐ-BGDĐT ngày 03 tháng 01 năm 2012, tiếp theo Tiếng Anh 7. Sách được biên soạn theo đường hướng giao tiếp, giúp học sinh sử dụng ngữ liệu (ngữ âm, từ vựng, ngữ pháp) để phát triển năng lực giao tiếp bằng tiếng Anh thông qua bốn kĩ năng nghe, nói, đọc và viết, trong đó, ưu tiên phát triển hai kĩ năng nghe và nói. Trong Tiếng Anh 8, Tập Hai, việc học là trung tâm, học sinh là chủ thể của quá trình dạy học, trong đó tâm lí lứa tuổi của học sinh Trung học cơ sở, các đặc điểm văn hóa của Việt Nam và của các nước trên thế giới, đặc biệt là của các nước nói tiếng Anh, được đặc biệt coi trọng.\r\nTiếng Anh 8, Tập Hai được biên soạn xoay quanh hai chủ điểm (Theme) gần gũi với học sinh: Our World và Visions of the Future. Mỗi chủ điểm được chia thành ba đơn vị bài học (Unit) tương ứng với ba chủ đề (Topic) của Chương trình. Sau mỗi chủ điểm là một bài ôn (Review) tập trung vào kiến thức ngôn ngữ và kĩ năng ngôn ngữ học sinh đã được học và rèn luyện.\r\nTiếng Anh 8, Tập Hai được biên soạn trên cơ sở những kinh nghiệm thực tiễn của việc dạy tiếng Anh  Trung học cơ sở ở Việt Nam với sự hợp tác chặt chẽ về chuyên môn và kĩ thuật của Tập đoàn Xuất bản Giáo dục Pearson.\r\n', '', 2, 1),
(45, 'Sách bài tập Tiếng Anh 8', 'sach-bai-tap-tieng-anh-8-45', 'Bia-TA8-SBT-1.png', 1, 8, 'Hoàng Văn Vân (Tổng Chủ biên), Nguyễn Quốc Tuấn (Chủ biên),…', 'GDVN', '2020', 'Tiếng Anh 8 – Sách bài tập (Tập Một) được biên soạn để giúp học sinh củng cố và mở rộng kiến thức ngôn ngữ và kĩ năng giao tiếp tiếng Anh các em đã học trong Tiếng Anh 8 - Sách học sinh (Tập Một). Sách gồm 6 đơn vị bài tập tương ứng với 6 đơn vị bài học trong Tiếng Anh 8 – Sách học sinh (Tập Một) và 2 bài tự kiểm tra (Test yourself ). \r\nMỖI ĐƠN VỊ BÀI TẬP GỒM 5 PHẦN:\r\n-	PHONETICS\r\n-	VOCABULARY & GRAMMAR\r\n-	SPEAKING\r\n-	READING\r\n-	WRITING\r\nTEST YOURSELF 1 và TEST YOURSELF 2 giúp học sinh tự kiểm tra những nội dung kiến thức và những yêu cầu về kĩ năng các em đã học sau mỗi 3 đơn vị bài học, đồng thời làm quen với các dạng bài kiểm tra tiếng Anh theo chuẩn quốc tế.\r\nCác bài tập trong Tiếng Anh 8 – Sách bài tập (Tập Một) đa dạng, phong phú, bám sát ngữ pháp, từ vựng và chủ đề trong Tiếng Anh 8 – Sách học sinh (Tập Một). Sách có nhiều tranh minh họa sinh động nhằm hỗ trợ học sinh liên hệ hình ảnh với từ ngữ và tình huống trong khi làm bài tập và thực hành giao tiếp.\r\n', '#', 1, 1),
(46, 'Sách bài tập Tiếng Anh 8', 'sach-bai-tap-tieng-anh-8-46', 'Bia-TA8-SBT-2.png', 1, 8, 'Hoàng Văn Vân (Tổng Chủ biên), Nguyễn Quốc Tuấn (Chủ biên),…', 'GDVN', '2020', 'TIẾNG ANH 8 – Sách bài Tập (Tập hAi) được biên soạn để giúp học sinh củng cố và mở rộng kiến thức ngôn ngữ và kĩ năng giao tiếp tiếng Anh các em đã học trong Tiếng Anh 8 – Sách học sinh (Tập hai). Sách gồm 6 đơn vị bài tập ứng với 6 đơn vị bài học trong Tiếng Anh 8 – Sách học sinh (Tập hai) và 2 bài tự kiểm tra (Test yourself ). \r\nMỗi đơn vị bài tập gồM 5 phần:\r\n-	PHONETICS\r\n-	VOCABULARY & GRAMMAR\r\n-	SPEAKING\r\n-	READING\r\n-	WRITING\r\nTEST YOURSELF 3 và TEST YOURSELF 4 giúp học sinh tự kiểm tra những nội dung kiến thức và những yêu cầu về kĩ năng các em đã học sau mỗi 3 đơn vị bài học, đồng thời làm quen với các dạng bài kiểm tra tiếng Anh theo chuẩn quốc tế.\r\nCác bài tập trong Tiếng Anh 8 – Sách bài tập (Tập hai) đa dạng, phong phú, bám sát ngữ pháp, từ vựng và chủ đề trong Tiếng Anh 8 –Sách học sinh (Tập hai). Sách có nhiều tranh minh họa sinh động nhằm hỗ trợ học sinh liên hệ hình ảnh với từ ngữ và tình huống trong khi làm bài tập và thực hành giao tiếp.\r\n', '#', 2, 1),
(47, 'Tiếng Anh 9', 'tieng-anh-9-47', 'Bia-TA9-SHS-1.png', 1, 9, 'Hoàng Văn Vân (Tổng Chủ biên), Nguyễn Quốc Tuấn (Chủ biên),…', 'GDVN', '2020', 'Tiếng Anh 9, Tập Một được Nhà xuất bản Giáo dục Việt Nam tổ chức biên soạn theo Chương trình Giáo dục phổ thông môn  Tiếng Anh thí điểm cấp Trung học cơ sở do Bộ Giáo dục và Đào tạo ban hành theo Quyết định số 01/QĐ-BGDĐT ngày 03 tháng 01 năm 2012, tiếp theo Tiếng Anh 8. Sách được biên soạn theo đường hướng giao tiếp, giúp học sinh sử dụng ngữ liệu (ngữ âm, từ vựng, ngữ pháp) để phát triển năng lực giao tiếp bằng tiếng Anh thông qua bốn kĩ năng nghe, nói, đọc và viết, trong đó, ưu tiên phát triển hai kĩ năng nghe và nói. Trong Tiếng Anh 9, Tập Một, việc học là trung tâm, học sinh là chủ thể của quá trình dạy học, trong đó tâm lí lứa tuổi của học sinh Trung học cơ sở, các đặc điểm văn hóa của Việt Nam và của các nước trên thế giới, đặc biệt là của các nước nói tiếng Anh, được đặc biệt  coi trọng.\r\nTiếng Anh 9, Tập Một được biên soạn xoay quanh hai chủ điểm (Theme) gần gũi với học sinh: Our Communities và Our Heritage. Mỗi chủ điểm được chia thành ba đơn vị bài học (Unit) tương ứng với ba chủ đề (Topic) của Chương trình. Sau mỗi chủ điểm là một bài ôn (Review) tập trung vào kiến thức ngôn ngữ và kĩ năng  ngôn ngữ học sinh đã được học và rèn luyện.\r\nTiếng Anh 9, Tập Một được biên soạn trên cơ sở những kinh nghiệm thực tiễn của việc dạy tiếng Anh  Trung học cơ sở ở Việt Nam với sự hợp tác chặt chẽ về chuyên môn và kĩ thuật của Tập đoàn Xuất bản Giáo dục Pearson.\r\n', '', 1, 1),
(48, 'Tiếng Anh 9', 'tieng-anh-9-48', 'Bia-TA9-SBT-2.png', 1, 9, 'Hoàng Văn Vân (Tổng Chủ biên), Nguyễn Quốc Tuấn (Chủ biên),…', 'GDVN', '2020', 'Tiếng Anh 9, Tập Hai được Nhà xuất bản Giáo dục Việt Nam tổ chức biên soạn theo Chương trình Giáo dục phổ thông môn  Tiếng Anh thí điểm cấp Trung học cơ sở do Bộ Giáo dục và Đào tạo ban hành theo Quyết định số 01/QĐ-BGDĐT ngày 03 tháng 01 năm 2012, tiếp theo Tiếng Anh 9, Tập Một. Sách được biên soạn theo đường hướng giao tiếp, giúp học sinh sử dụng ngữ liệu (ngữ âm, từ vựng, ngữ pháp) để phát triển năng lực giao tiếp bằng tiếng Anh thông qua bốn kĩ năng nghe, nói, đọc và viết, trong đó, ưu tiên phát triển hai kĩ năng nghe và nói. Trong Tiếng Anh 9, Tập Hai, việc học là trung tâm, học sinh là chủ thể của quá trình dạy học, trong đó tâm lí lứa tuổi của học sinh Trung học cơ sở, các đặc điểm văn hóa của Việt Nam và của các nước trên thế giới, đặc biệt là của các nước nói tiếng Anh, được đặc biệt  coi trọng.\r\nTiếng Anh 9, Tập Hai được biên soạn xoay quanh hai chủ điểm (Theme) gần gũi với học sinh: Our World và Vision of the Future. Mỗi chủ điểm được chia thành ba đơn vị bài học (Unit) tương ứng với ba chủ đề (Topic) của Chương trình. Sau mỗi chủ điểm là một bài ôn (Review) tập trung vào kiến thức ngôn ngữ và kĩ năng  ngôn ngữ học sinh đã được học và rèn luyện.\r\nTiếng Anh 9, Tập Hai được biên soạn trên cơ sở những kinh nghiệm thực tiễn của việc dạy tiếng Anh  Trung học cơ sở ở Việt Nam với sự hợp tác chặt chẽ về chuyên môn và kĩ thuật của Tập đoàn Xuất bản Giáo dục Pearson.\r\n', '#', 2, 1),
(49, 'Sách bài tập Tiếng Anh 9', 'sach-bai-tap-tieng-anh-9-49', 'Bia-TA9-SBT-1.png', 1, 9, 'Hoàng Văn Vân (Tổng Chủ biên), Nguyễn Quốc Tuấn (Chủ biên),…', 'GDVN', '2020', 'TIẾNG ANH 9 – Sách bài Tập (Tập MỘT) được biên soạn để giúp học sinh củng cố và mở rộng kiến thức ngôn ngữ và kĩ năng giao tiếp tiếng Anh các em đã học trong Tiếng Anh 9 – Sách học sinh  (Tập Một). Sách gồm 6 đơn vị bài tập ứng với 6 đơn vị bài học trong Tiếng Anh 9 – Sách học sinh (Tập Một) và 2 bài tự kiểm tra  (Test yourself). \r\nMỖI ĐƠN VỊ BÀI TẬP GỒM 5 PHẦN:\r\n-	PHONETICS\r\n-	VOCABULARY & GRAMMAR\r\n-	SPEAKING\r\n-	READING\r\n-	WRITING\r\nTEST YOURSELf 1 và TEST YOURSELf 2 giúp học sinh tự kiểm tra những nội dung kiến thức và những yêu cầu về kĩ năng các em đã học sau mỗi 3 đơn vị bài học, đồng thời làm quen với các dạng bài kiểm tra tiếng Anh theo chuẩn quốc tế.\r\nCác bài tập trong Tiếng Anh 9 – Sách bài tập (Tập Một) đa dạng, phong phú, bám sát ngữ pháp, từ vựng và chủ đề trong Tiếng Anh 9 –Sách học sinh (Tập Một). Sách có nhiều tranh minh họa sinh động nhằm hỗ trợ học sinh liên hệ hình ảnh với từ ngữ và tình huống trong khi làm bài tập và thực hành giao tiếp.\r\n\r\n\r\n', '#', 1, 1),
(50, 'Sách bài tập Tiếng Anh 9', 'sach-bai-tap-tieng-anh-9-50', 'Bia-TA9-SBT-2.png', 1, 9, 'Hoàng Văn Vân (Tổng Chủ biên), Nguyễn Quốc Tuấn (Chủ biên),…', 'GDVN', '2020', 'TIẾNG ANH 9 – Sách bài Tập (Tập hAi) được biên soạn để giúp học sinh củng cố và mở rộng kiến thức ngôn ngữ và kĩ năng giao tiếp tiếng Anh các em đã học trong Tiếng Anh 9 – Sách học sinh  (Tập hai). Sách gồm 6 đơn vị bài tập ứng với 6 đơn vị bài học trong Tiếng Anh 9 – Sách học sinh (Tập hai) và 2 bài tự kiểm tra  (Test yourself). \r\nMỖI ĐƠN VỊ BÀI TẬP GỒM 5 PHẦN:\r\n-	PHONETICS\r\n-	VOCABULARY & GRAMMAR\r\n-	SPEAKING\r\n-	READING\r\n-	WRITING\r\nTEST YOURSELF 3 và TEST YOURSELF 4 giúp học sinh tự kiểm tra những nội dung kiến thức và những yêu cầu về kĩ năng các em đã học sau mỗi 3 đơn vị bài học, đồng thời làm quen với các dạng bài kiểm tra tiếng Anh theo chuẩn quốc tế.\r\nCác bài tập trong Tiếng Anh 9 – Sách bài tập (Tập hai) đa dạng, phong phú, bám sát ngữ pháp, từ vựng và chủ đề trong Tiếng Anh 9 –Sách học sinh (Tập hai). Sách có nhiều tranh minh họa sinh động nhằm hỗ trợ học sinh liên hệ hình ảnh với từ ngữ và tình huống trong khi làm bài tập và thực hành giao tiếp.\r\n\r\n', '#', 2, 1),
(51, 'Tiếng Anh 10', 'tieng-anh-10-51', 'Bia-TA10-SHS-1.png', 1, 10, 'Hoàng Văn Vân (Tổng Chủ biên), Nguyễn Quốc Tuấn (Chủ biên),…', 'GDVN', '2020', 'Tiếng Anh 10, Tập Một là cuốn sách đầu tiên được Nhà xuất bản Giáo dục Việt Nam tổ chức biên soạn theo Chương trình Giáo dục phổ thông môn Tiếng Anh thí điểm cấp Trung học phổ thông do Bộ Giáo dục và Đào tạo ban hành theo Quyết định số 5209/QĐ-BGDĐT ngày 23 tháng 11 năm 2012, tiếp theo Chương trình tiếng Anh tiểu học và Chương trình tiếng Anh trung học cơ sở. Sách được biên soạn theo đường hướng giao tiếp, giúp học sinh, thông qua sử dụng ngữ liệu (ngữ âm, từ vựng, ngữ pháp), phát triển năng lực giao tiếp bằng tiếng Anh dưới bốn hình thức nghe, nói, đọc và viết. Tiếng Anh 10, Tập Một chủ trương lấy HỌC làm trung tâm, trong đó học sinh là chủ thể của quá trình dạy - học, giáo viên là người hướng dẫn, người tổ chức các hoạt động trên lớp, giúp học sinh giao tiếp có hiệu quả. Trong Tiếng Anh 10, Tập Một, tâm lí lứa tuổi của học sinh và các đặc điểm văn hóa của Việt Nam và của các nước trên thế giới, đặc biệt là của các nước nói tiếng Anh và các nước trong khu vực, được coi trọng.\r\nTiếng Anh 10, Tập Một được biên soạn xoay quanh hai chủ điểm (theme) gần gũi với học sinh: Our Lives và Our Society. Mỗi chủ điểm được chia thành hai hoặc ba đơn bị bài học (Unit) tương ứng với các chủ đề (topic) gợi ý trong Chương trình. Sau mỗi chủ điểm là một bài ôn (Review) tập trung vào kiến thức ngôn ngữ và kĩ năng ngôn ngữ học sinh đã được học và rèn luyện.\r\nTiếng Anh 10, Tập Một được biên soạn trên cơ sở những kinh nghiệm thực tiễn của việc dạy và học tiếng Anh trung phổ thông ở Việt Nam. Sách nhận được sự hợp tác chặt chẽ về chuyên môn và kĩ thuật của Nhà xuất bản Pearson và Hội đồng Anh.\r\n', '#', 1, 1),
(52, 'Tiếng Anh 10', 'tieng-anh-10-52', 'Bia-TA10-SHS-2.png', 1, 10, 'Hoàng Văn Vân (Tổng Chủ biên), Nguyễn Quốc Tuấn (Chủ biên),…', 'GDVN', '2020', 'Tiếng Anh 10, Tập Hai là cuốn sách thứ hai được Nhà xuất bản Giáo dục Việt Nam tổ chức biên soạn theo Chương trình Giáo dục phổ thông môn Tiếng Anh thí điểm cấp Trung học phổ thông do Bộ Giáo dục và Đào tạo ban hành theo Quyết định số 5209/QĐ-BGDĐT ngày 23 tháng 11 năm 2012, tiếp theo Chương trình tiếng Anh Tiểu học và Chương trình tiếng Anh Trung học cơ sở. Sách được biên soạn theo đường hướng giao tiếp, giúp học sinh, thông qua sử dụng ngữ liệu (ngữ âm, từ vựng, ngữ pháp), phát triển năng lực giao tiếp bằng tiếng Anh dưới bốn hình thức nghe, nói, đọc và viết. Tiếng Anh 10 chủ trương lấy HỌC làm trung tâm, trong đó học sinh là chủ thể của quá trình dạy - học, giáo viên là người hướng dẫn, người tổ chức các hoạt động trên lớp, giúp học sinh giao tiếp có hiệu quả. Trong Tiếng Anh 10, tâm lí lứa tuổi của học sinh và các đặc điểm văn hóa của Việt Nam và của các nước trên thế giới, đặc biệt là của các nước nói tiếng Anh và các nước trong khu vực, được coi trọng.\r\nTiếng Anh 10, Tập Hai được biên soạn xoay quanh ba chủ điểm (theme) gần gũi với học sinh: Our Society, Our Environment và Our Future. Mỗi chủ điểm được thể hiện ở một đến ba đơn bị bài học (Unit) tương ứng với các chủ đề (topic) gợi ý trong Chương trình. Sau mỗi hai hoặc ba đơn vị bài học là một bài ôn (Review) tập trung vào kiến thức ngôn ngữ và kĩ năng ngôn ngữ học sinh đã được học và rèn luyện.\r\nTiếng Anh 10, Tập Hai được biên soạn trên cơ sở những kinh nghiệm thực tiễn của việc dạy và học tiếng Anh trong trường phổ thông ở Việt Nam. Sách nhận được sự hợp tác chặt chẽ về chuyên môn và kĩ thuật của Nhà xuất bản Pearson.\r\n', '#', 2, 1),
(53, 'Sách bài tập Tiếng Anh 10', 'sach-bai-tap-tieng-anh-10-53', 'Bia-TA10-SBT-1.png', 1, 11, 'Hoàng Văn Vân (Tổng Chủ biên), Nguyễn Quốc Tuấn (Chủ biên),…', 'GDVN', '2020', 'Tiếng Anh 10 – Sách bài tập (Tập 1) được biên soạn để giúp học sinh củng cố và mở rộng kiến thức ngôn ngữ và kĩ năng giao tiếp tiếng Anh các em đã học trong Tiếng Anh 10 – Sách học sinh (Tập 1). Sách gồm 5 đơn vị bài tập ứng với 5 đơn vị bài học trong Tiếng Anh 10 – Sách học sinh (Tập 1) và 2 bài tự kiểm tra (Test yourself). \r\nMỗi đơn vị bài tập gồm 5 phần:\r\nA.	PRONUNCIATION\r\nB.	VOCABULARY & GRAMMAR\r\nC.	SPEAKING\r\nD.	READING\r\nE.	WRITING\r\nCác bài tập trong Tiếng Anh 10 – Sách bài tập (Tập 1) đa dạng, phong phú, bám sát ngữ pháp, từ vựng và chủ đề trong Tiếng Anh 10 – Sách học sinh (Tập 1). Sách được biên soạn theo hình thức tương tác để hỗ trợ học sinh liên hệ những gì mình đang thực hành với ngôn cảnh và tình huống trong khi làm bài tập và thực hành giao tiếp.\r\n', '#', 1, 1),
(54, 'Sách bài tập Tiếng Anh 10', 'sach-bai-tap-tieng-anh-10-54', 'Bia-TA10-SBT-2.png', 1, 10, 'Hoàng Văn Vân (Tổng Chủ biên), Nguyễn Quốc Tuấn (Chủ biên),…', 'GDVN', '2020', 'Tiếng Anh 10 – Sách bài tập (Tập 2) được biên soạn để giúp học sinh củng cố và mở rộng kiến thức ngôn ngữ và kĩ năng giao tiếp tiếng Anh các em đã học trong Tiếng Anh 10 – Sách học sinh (Tập 2). Sách gồm 5 đơn vị bài tập ứng với 5 đơn vị bài học trong Tiếng Anh 10 – Sách học sinh (Tập 2).\r\nMỗi đơn vị bài tập gồm 5 phần:\r\nA.	PRONUNCIATION\r\nB.	VOCABULARY & GRAMMAR\r\nC.	SPEAKING\r\nD.	READING\r\nE.	WRITING\r\nCác bài tập trong Tiếng Anh 10 – Sách bài tập (Tập 2) đa dạng, phong phú, bám sát ngữ pháp, từ vựng và chủ đề trong Tiếng Anh 10 – Sách học sinh (Tập 2). Sách được biên soạn theo hình thức tương tác để hỗ trợ học sinh liên hệ những gì mình đang thực hành với ngôn cảnh và tình huống trong khi làm bài tập và thực hành giao tiếp.\r\n', '#', 2, 1),
(55, 'Tiếng Anh 11', 'tieng-anh-11-55', 'Bia-TA11-SHS-1.png', 1, 11, 'Hoàng Văn Vân (Tổng Chủ biên), Nguyễn Quốc Tuấn (Chủ biên),…', 'GDVN', '2020', 'Tiếng Anh 11, Tập Một là cuốn sách đầu tiên được Nhà xuất bản Giáo dục Việt Nam tổ chức biên soạn theo Chương trình Giáo dục phổ thông môn Tiếng Anh thí điểm cấp Trung học phổ thông do Bộ Giáo dục và Đào tạo ban hành theo Quyết định số 5209/QĐ-BGDĐT ngày 23 tháng 11 năm 2012, tiếp theo Chương trình tiếng Anh tiểu học và Chương trình tiếng Anh trung học cơ sở. Sách được biên soạn theo đường hướng giao tiếp, giúp học sinh, thông qua sử dụng ngữ liệu (ngữ âm, từ vựng, ngữ pháp), phát triển năng lực giao tiếp bằng tiếng Anh dưới bốn hình thức nghe, nói, đọc và viết. Tiếng Anh 11, Tập Một chủ trương lấy HỌC làm trung tâm, trong đó học sinh là chủ thể của quá trình dạy - học, giáo viên là người hướng dẫn, người tổ chức các hoạt động trên lớp, giúp học sinh giao tiếp có hiệu quả. Trong Tiếng Anh 11, Tập Một, tâm lí lứa tuổi của học sinh và các đặc điểm văn hoá của Việt Nam và của các nước trên thế giới, đặc biệt là của các nước nói tiếng Anh và các nước trong khu vực, được coi trọng.\r\nTiếng Anh 11, Tập Một được biên soạn xoay quanh hai chủ điểm (theme) gần gũi với học sinh: Our Lives và Our Society. Mỗi chủ điểm được chia thành hai hoặc ba đơn vị bài học (Unit) tương ứng với các chủ đề (topic) gợi ý trong Chương trình. Sau mỗi chủ điểm là một bài ôn (Review) tập trung vào kiến thức ngôn ngữ và kĩ năng ngôn ngữ học sinh đã được học và rèn luyện.\r\nTiếng Anh 11, Tập Một được biên soạn trên cơ sở những kinh nghiệm thực tiễn của việc dạy và học tiếng Anh trung học phổ thông ở Việt Nam. Sách nhận được sự hợp tác chặt chẽ về chuyên môn và kĩ thuật của Nhà xuất bản Pearson và Hội đồng Anh.\r\n', '#', 1, 1),
(56, 'Tiếng Anh 11', 'tieng-anh-11-56', 'Bia-TA11-SHS-2.png', 1, 11, 'Hoàng Văn Vân (Tổng Chủ biên), Nguyễn Quốc Tuấn (Chủ biên),…', 'GDVN', '2020', 'Tiếng Anh 11, Tập Hai là cuốn sách đầu tiên được Nhà xuất bản Giáo dục Việt Nam tổ chức biên soạn theo Chương trình Giáo dục phổ thông môn Tiếng Anh thí điểm cấp Trung học phổ thông do Bộ Giáo dục và Đào tạo ban hành theo Quyết định số 5209/QĐ-BGDĐT ngày 23 tháng 11 năm 2012, tiếp theo Chương trình tiếng Anh tiểu học và Chương trình tiếng Anh trung học cơ sở. Sách được biên soạn theo đường hướng giao tiếp, giúp học sinh, thông qua sử dụng ngữ liệu (ngữ âm, từ vựng, ngữ pháp), phát triển năng lực giao tiếp bằng tiếng Anh dưới bốn hình thức nghe, nói, đọc và viết. Tiếng Anh 11, Tập Hai chủ trương lấy HỌC làm trung tâm, trong đó học sinh là chủ thể của quá trình dạy - học, giáo viên là người hướng dẫn, người tổ chức các hoạt động trên lớp, giúp học sinh giao tiếp có hiệu quả. Trong Tiếng Anh 11, Tập Hai, tâm lí lứa tuổi của học sinh và các đặc điểm văn hoá của Việt Nam và của các nước trên thế giới, đặc biệt là của các nước nói tiếng Anh và các nước trong khu vực, được coi trọng.\r\nTiếng Anh 11, Tập Hai được biên soạn xoay quanh hai chủ điểm (theme) gần gũi với học sinh: Our Environment và Our Future. Mỗi chủ điểm được chia thành hai hoặc ba đơn vị bài học (Unit) tương ứng với các chủ đề (topic) gợi ý trong Chương trình. Sau mỗi chủ điểm là một bài ôn (Review) tập trung vào kiến thức ngôn ngữ và kĩ năng ngôn ngữ học sinh đã được học và rèn luyện.\r\nTiếng Anh 11, Tập Hai được biên soạn trên cơ sở những kinh nghiệm thực tiễn của việc dạy và học tiếng Anh trung học phổ thông ở Việt Nam. Sách nhận được sự hợp tác chặt chẽ về chuyên môn và kĩ thuật của Nhà xuất bản Pearson và Hội đồng Anh.\r\n', '#', 2, 1),
(57, 'Sách bài tập Tiếng Anh 11', 'sach-bai-tap-tieng-anh-11-57', 'Bia-TA11-SBT-1.png', 1, 11, 'Hoàng Văn Vân (Tổng Chủ biên), Nguyễn Quốc Tuấn (Chủ biên),…', 'GDVN', '2020', 'Tiếng Anh 11 – Sách bài tập (Tập Một) được biên soạn để giúp học sinh củng cố và mở rộng kiến thức ngôn ngữ và kĩ năng giao tiếp tiếng Anh các em đã học trong Tiếng Anh 11 – Sách học sinh (Tập Một). Sách gồm 5 đơn vị bài tập ứng với 5 đơn vị bài học trong Tiếng Anh 11 – Sách học sinh (Tập Một).\r\nMỗi đơn vị bài tập gồm 5 phần:\r\nA.	PRONUNCIATION\r\nB.	VOCABULARY & GRAMMAR\r\nC.	SPEAKING\r\nD.	READING\r\nE.	WRITING\r\nCác bài tập trong Tiếng Anh 11 – Sách bài tập (Tập Một) đa dạng, phong phú, bám sát ngữ pháp, từ vựng và chủ đề trong Tiếng Anh 11 – Sách học sinh (Tập Một). Sách được biên soạn theo hình thức tương tác để hỗ trợ học sinh liên hệ những gì mình đang thực hành với ngôn cảnh và tình huống trong khi làm bài tập và thực hành giao tiếp.\r\n', '#', 1, 1),
(58, 'Sách bài tập Tiếng Anh ', 'sach-bai-tap-tieng-anh-58', 'Bia-TA11-SBT-2.png', 1, 11, 'Hoàng Văn Vân (Tổng Chủ biên), Nguyễn Quốc Tuấn (Chủ biên),…', 'GDVN', '2020', 'Tiếng Anh 11 – Sách bài tập (Tập Hai) được biên soạn để giúp học sinh củng cố và mở rộng kiến thức ngôn ngữ và kĩ năng giao tiếp tiếng Anh các em đã học trong Tiếng Anh 11 – Sách học sinh (Tập Hai). Sách gồm 5 đơn vị bài tập ứng với 5 đơn vị bài học trong Tiếng Anh 11 – Sách học sinh (Tập Hai).\r\nMỗi đơn vị bài tập gồm 5 phần:\r\nA.	PRONUNCIATION\r\nB.	VOCABULARY & GRAMMAR\r\nC.	SPEAKING\r\nD.	READING\r\nE.	WRITING\r\nCác bài tập trong Tiếng Anh 11 – Sách bài tập (Tập Hai) đa dạng, phong phú, bám sát ngữ pháp, từ vựng và chủ đề trong Tiếng Anh 11 – Sách học sinh (Tập Hai). Sách được biên soạn theo hình thức tương tác để hỗ trợ học sinh liên hệ những gì mình đang thực hành với ngôn cảnh và tình huống trong khi làm bài tập và thực hành giao tiếp.\r\n', '#', 2, 1),
(59, 'Tiếng Anh 12', 'tieng-anh-12-59', 'Bia-TA12-SHS-1.png', 1, 12, 'Hoàng Văn Vân (Tổng Chủ biên), Nguyễn Quốc Tuấn (Chủ biên),…', 'GDVN', '2020', 'Tiếng Anh 12, Tập Một là cuốn sách đầu tiên được Nhà xuất bản Giáo dục Việt Nam tổ chức biên soạn theo Chương trình Giáo dục phổ thông môn Tiếng Anh thí điểm cấp Trung học phổ thông do Bộ Giáo dục và Đào tạo ban hành theo Quyết định số 5209/QĐ-BGDĐT ngày 23 tháng 11 năm 2012, tiếp theo Chương trình tiếng Anh tiểu học và Chương trình tiếng Anh trung học cơ sở. Sách được biên soạn theo đường hướng giao tiếp, giúp học sinh, thông qua sử dụng ngữ liệu (ngữ âm, từ vựng, ngữ pháp), phát triển năng lực giao tiếp bằng tiếng Anh dưới bốn hình thức nghe, nói, đọc và viết. Tiếng Anh 12, Tập Một chủ trương lấy HỌC làm trung tâm, trong đó học sinh là chủ thể của quá trình dạy - học, giáo viên là người hướng dẫn, người tổ chức các hoạt động trên lớp, giúp học sinh giao tiếp có hiệu quả. Trong Tiếng Anh 12, Tập Một, tâm lí lứa tuổi của học sinh và các đặc điểm văn hóa của Việt Nam và của các nước trên thế giới, đặc biệt là của các nước nói tiếng Anh và các nước trong khu vực, được coi trọng.\r\nTiếng Anh 12, Tập Một được biên soạn xoay quanh hai chủ điểm (theme) gần gũi với học sinh: Our Lives và Our Society. Mỗi chủ điểm được chia thành hai hoặc ba đơn bị bài học (Unit) tương ứng với các chủ đề (topic) gợi ý trong Chương trình. Sau mỗi chủ điểm là một bài ôn (Review) tập trung vào kiến thức ngôn ngữ và kĩ năng ngôn ngữ học sinh đã được học và rèn luyện.\r\nTiếng Anh 12, Tập Một được biên soạn trên cơ sở những kinh nghiệm thực tiễn của việc dạy và học tiếng Anh trung học phổ thông ở Việt Nam. Sách nhận được sự hợp tác chặt chẽ về chuyên môn và kĩ thuật của Nhà xuất bản Pearson và Hội đồng Anh.\r\n', '#', 1, 1),
(60, 'Tiếng Anh 12', 'tieng-anh-12-60', 'Bia-TA12-SHS-2.png', 1, 12, 'Hoàng Văn Vân (Tổng Chủ biên), Nguyễn Quốc Tuấn (Chủ biên),…', 'GDVN', '2020', 'Tiếng Anh 12, Tập Hai là cuốn sách được Nhà xuất bản Giáo dục Việt Nam tổ chức biên soạn theo Chương trình Giáo dục phổ thông môn Tiếng Anh thí điểm cấp Trung học phổ thông do Bộ Giáo dục và Đào tạo ban hành theo Quyết định số 5209/QĐ-BGDĐT ngày 23 tháng 11 năm 2012, tiếp theo Chương trình tiếng Anh tiểu học và Chương trình tiếng Anh trung học cơ sở. Sách được biên soạn theo đường hướng giao tiếp, giúp học sinh, thông qua sử dụng ngữ liệu (ngữ âm, từ vựng, ngữ pháp), phát triển năng lực giao tiếp bằng tiếng Anh dưới bốn hình thức nghe, nói, đọc và viết. Tiếng Anh 12, Tập Hai chủ trương lấy HỌC làm trung tâm, trong đó học sinh là chủ thể của quá trình dạy - học, giáo viên là người hướng dẫn, người tổ chức các hoạt động trên lớp, giúp học sinh giao tiếp có hiệu quả. Trong Tiếng Anh 12, Tập Hai, tâm lí lứa tuổi của học sinh và các đặc điểm văn hóa của Việt Nam và của các nước trên thế giới, đặc biệt là của các nước nói tiếng Anh và các nước trong khu vực, được coi trọng.\r\nTiếng Anh 12, Tập Hai được biên soạn xoay quanh hai chủ điểm (theme) gần gũi với học sinh: Our Environment và Our Future. Mỗi chủ điểm được chia thành hai hoặc ba đơn bị bài học (Unit) tương ứng với các chủ đề (topic) gợi ý trong Chương trình. Sau mỗi chủ điểm là một bài ôn (Review) tập trung vào kiến thức ngôn ngữ và kĩ năng ngôn ngữ học sinh đã được học và rèn luyện.\r\nTiếng Anh 12, Tập Hai được biên soạn trên cơ sở những kinh nghiệm thực tiễn của việc dạy và học tiếng Anh trung học phổ thông ở Việt Nam. Sách nhận được sự hợp tác chặt chẽ về chuyên môn và kĩ thuật của Nhà xuất bản Pearson và Hội đồng Anh.\r\n', '', 2, 1),
(61, 'Sách bài tập Tiếng Anh 12', 'sach-bai-tap-tieng-anh-12-61', 'Bia-TA12-SBT-1.png', 1, 12, 'Hoàng Văn Vân (Tổng Chủ biên), Nguyễn Quốc Tuấn (Chủ biên),…', 'GDVN', '2020', 'Tiếng Anh 12 – Sách bài tập (Tập Một) được biên soạn để giúp học sinh củng cố và mở rộng kiến thức ngôn ngữ và kĩ năng giao tiếp tiếng Anh các em đã học trong Tiếng Anh 12 – Sách học sinh (Tập Một). Sách gồm 5 đơn vị bài tập ứng với 5 đơn vị bài học trong Tiếng Anh 12 – Sách học sinh (Tập Một).\r\nMỗi đơn vị bài tập gồm 5 phần:\r\nA.	PRONUNCIATION\r\nB.	VOCABULARY & GRAMMAR\r\nC.	SPEAKING\r\nD.	READING\r\nE.	WRITING\r\nCác bài tập trong Tiếng Anh 12– Sách bài tập (Tập Một) đa dạng, phong phú, bám sát ngữ pháp, từ vựng và chủ đề trong Tiếng Anh 12 – Sách học sinh (Tập Một). Sách được biên soạn theo hình thức tương tác để hỗ trợ học sinh liên hệ những gì mình đang thực hành với ngôn cảnh và tình huống trong khi làm bài tập và thực hành giao tiếp.\r\n', '', 1, 1),
(62, 'Sách bài tập Tiếng Anh 12', 'sach-bai-tap-tieng-anh-12-62', 'Bia-TA12-SBT-2.png', 1, 12, 'Hoàng Văn Vân (Tổng Chủ biên), Nguyễn Quốc Tuấn (Chủ biên),…', 'GDVN', '2020', 'Tiếng Anh 12 – Sách bài tập (Tập Hai) được biên soạn để giúp học sinh củng cố và mở rộng kiến thức ngôn ngữ và kĩ năng giao tiếp tiếng Anh các em đã học trong Tiếng Anh 12 – Sách học sinh (Tập Hai). Sách gồm 5 đơn vị bài tập ứng với 5 đơn vị bài học trong Tiếng Anh 12 – Sách học sinh (Tập Hai).\r\nMỗi đơn vị bài tập gồm 5 phần:\r\nA.	PRONUNCIATION\r\nB.	VOCABULARY & GRAMMAR\r\nC.	SPEAKING\r\nD.	READING\r\nE.	WRITING\r\nCác bài tập trong Tiếng Anh 12– Sách bài tập (Tập Hai) đa dạng, phong phú, bám sát ngữ pháp, từ vựng và chủ đề trong Tiếng Anh 12 – Sách học sinh (Tập Hai). Sách được biên soạn theo hình thức tương tác để hỗ trợ học sinh liên hệ những gì mình đang thực hành với ngôn cảnh và tình huống trong khi làm bài tập và thực hành giao tiếp.\r\n\r\n', '#', 2, 1);

-- --------------------------------------------------------

--
-- Cấu trúc bảng cho bảng `category`
--

CREATE TABLE `category` (
  `id` int(11) NOT NULL,
  `name` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `slug` varchar(550) COLLATE utf8_unicode_ci DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Đang đổ dữ liệu cho bảng `category`
--

INSERT INTO `category` (`id`, `name`, `slug`) VALUES
(1, 'Sách Giáo Khoa', NULL),
(2, 'Sách Tham Khảo - Bổ Trợ', NULL),
(3, 'Sách Tăng Cường', NULL);

-- --------------------------------------------------------

--
-- Cấu trúc bảng cho bảng `contact`
--

CREATE TABLE `contact` (
  `id` int(11) NOT NULL,
  `name` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `email` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `subject` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `message` text COLLATE utf8_unicode_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- --------------------------------------------------------

--
-- Cấu trúc bảng cho bảng `news`
--

CREATE TABLE `news` (
  `id` int(11) NOT NULL,
  `name` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `date` int(11) NOT NULL,
  `description` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `content` longtext COLLATE utf8_unicode_ci NOT NULL,
  `source` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `type` int(1) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- --------------------------------------------------------

--
-- Cấu trúc bảng cho bảng `user`
--

CREATE TABLE `user` (
  `idUser` int(11) NOT NULL,
  `name` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `email` varchar(150) COLLATE utf8_unicode_ci DEFAULT NULL,
  `pass` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `role` int(1) NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Đang đổ dữ liệu cho bảng `user`
--

INSERT INTO `user` (`idUser`, `name`, `email`, `pass`, `role`) VALUES
(1, 'nhat anh 1', 'daonhatanh630@gmail.com', 'asdasd', 1),
(4, 'nhan', 'tranquangnhan1606@gmail.com', '111111', 1),
(10, 'Dao Nhat Anh', 'anhdnps12765@fpt.edu.vn', 'asdasd', 0),
(11, 'Dao Anh', 'chikon555@gmail.com', 'asdasd', 0);

--
-- Chỉ mục cho các bảng đã đổ
--

--
-- Chỉ mục cho bảng `book`
--
ALTER TABLE `book`
  ADD PRIMARY KEY (`id`),
  ADD KEY `fk_book_cate` (`idcate`);

--
-- Chỉ mục cho bảng `category`
--
ALTER TABLE `category`
  ADD PRIMARY KEY (`id`);

--
-- Chỉ mục cho bảng `contact`
--
ALTER TABLE `contact`
  ADD PRIMARY KEY (`id`);

--
-- Chỉ mục cho bảng `news`
--
ALTER TABLE `news`
  ADD PRIMARY KEY (`id`);

--
-- Chỉ mục cho bảng `user`
--
ALTER TABLE `user`
  ADD PRIMARY KEY (`idUser`);

--
-- AUTO_INCREMENT cho các bảng đã đổ
--

--
-- AUTO_INCREMENT cho bảng `book`
--
ALTER TABLE `book`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=142;

--
-- AUTO_INCREMENT cho bảng `category`
--
ALTER TABLE `category`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=7;

--
-- AUTO_INCREMENT cho bảng `contact`
--
ALTER TABLE `contact`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT cho bảng `news`
--
ALTER TABLE `news`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT cho bảng `user`
--
ALTER TABLE `user`
  MODIFY `idUser` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=12;

--
-- Các ràng buộc cho các bảng đã đổ
--

--
-- Các ràng buộc cho bảng `book`
--
ALTER TABLE `book`
  ADD CONSTRAINT `fk_book_cate` FOREIGN KEY (`idcate`) REFERENCES `category` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
